// Политики жизненного цикла моделей ДВИЖКОВ платформы (apps/api/src/core/*): личность и
// сессии, права, уведомления, файлы, голос и звонки, джобы, хроника, поиск, подтверждения,
// ссылки наружу, решения, подпись, офисные документы, тарифы, кабинет, аналитика, ключи,
// вебхуки, согласия, идемпотентность, журнал безопасности, видимость.
import {
  BY_REFERENCE,
  CASCADE,
  CASCADE_FK,
  CONSENT,
  CONTRACT,
  FOREVER,
  NOT_TENANT,
  YEARS,
  batched,
  byUser,
  byWorkspace,
  deep,
  dropPartition,
  eraseBy,
  eraseHook,
  forDays,
  global,
  guard,
  interest,
  keep,
  law,
  legalFloor,
  noSubject,
  notEnforced,
  polymorphic,
  pseudonymizeBy,
  pseudonymizeHook,
  retainLegal,
  scoped,
  shallow,
  shred,
  subject,
  tenantBatched,
  tenantHook,
  tenantRetain,
  via,
  withParent,
} from './helpers';
import { BLOB_LIFECYCLE } from './stores';
import type { LifecyclePolicyInput } from './types';
import { CHANGE_PERSON_ID_KEYS, CHATTER_PERSON_ID_KEYS, NOTIFICATION_PERSON_ID_KEYS } from './person-refs';

export const CORE_LIFECYCLE = {
  // ================= Личность, сессии, устройства =================
  User: {
    owner: 'core/users',
    version: 1,
    dataClass: 'identity_pii',
    ownerKey: global('identity directory: login resolves the person before any cell is known'),
    subjects: [subject('id', 'owner')],
    legalBasis: CONSENT,
    retention: keep(),
    // Строка остаётся томбстоуном (ссылки задач, чатов, организаций целы); ПДн стираются, KEK уничтожается
    onSubjectErasure: pseudonymizeHook(
      'users.account',
      'firstName',
      'lastName',
      'middleName',
      'phone',
      'email',
      'iin',
      'residentialAddress',
      'idDocNumber',
      'idDocIssuedBy',
      'idDocIssuedAt',
      'avatar',
      'bio',
      'city',
      'dateOfBirth',
      'maritalStatus',
      'socialLinks',
      'password',
    ),
    onTenantPurge: NOT_TENANT,
    edges: [
      deep('Bot', 'userId'),
      deep('CalendarEvent', 'userId'),
      deep('ChatMember', 'userId'),
      deep('Circle', 'ownerId'),
      deep('ContactBlock', 'blockedId'),
      deep('ContactBlock', 'blockerId'),
      deep('ContactInvitation', 'toUserId'),
      deep('ContactInvitation', 'fromUserId'),
      deep('ContactLink', 'userBId'),
      deep('ContactLink', 'userAId'),
      deep('GoogleConnection', 'userId'),
      shallow('Message', 'authorId'),
      deep('NotificationDevice', 'userId'),
      deep('NotificationPreference', 'userId'),
      deep('NotificationSubscription', 'userId'),
      deep('Notification', 'userId'),
      deep('Resource', 'ownerId'),
      deep('ScheduledMessage', 'authorId'),
      deep('Session', 'userId'),
      deep('StaffAssignment', 'userId'),
      deep('StaffDeputy', 'deputyUserId'),
      deep('TaskParticipant', 'userId'),
      deep('Task', 'creatorId'),
      deep('UserDevice', 'userId'),
      deep('UserNotificationSettings', 'userId'),
      deep('UserPaymentCard', 'userId'),
      deep('UserRole', 'userId'),
      deep('WorkspaceInvitation', 'toUserId'),
      deep('WorkspaceInvitation', 'invitedBy'),
      deep('WorkspaceMember', 'userId'),
      deep('Workspace', 'ownerId'),
      // Полиморфные владения человека (ownerType = user) — без FK, добирает оркестратор стирания
      { to: 'DriveSpace', kind: 'deep', via: 'ownerId' },
      { to: 'NoteSpace', kind: 'deep', via: 'ownerId' },
      { to: 'FinBook', kind: 'deep', via: 'ownerId' },
      { to: 'FileObject', kind: 'refcount', via: 'ownerId' },
      { to: 'Document', kind: 'deep', via: 'ownerId' },
      { to: 'VoiceRecording', kind: 'deep', via: 'ownerId' },
      { to: 'WishItem', kind: 'deep', via: 'ownerId' },
      { to: 'Shop', kind: 'deep', via: 'ownerId' },
      { to: 'CardSkinInstance', kind: 'deep', via: 'ownerId' },
      { to: 'Account', kind: 'shallow', via: 'ownerId' },
      { to: 'ShareLink', kind: 'async_delete', via: 'ownerId' },
      { to: 'VisibilityPolicy', kind: 'deep', via: 'ownerId' },
      { to: 'AnalyticsIdentityLink', kind: 'async_delete', via: 'userId' },
      { to: 'AnalyticsRollupActorDay', kind: 'async_delete', via: 'actorId' },
      { to: 'SubjectSubscription', kind: 'async_delete', via: 'subjectId' },
      { to: 'EntitlementGrant', kind: 'async_delete', via: 'subjectId' },
      { to: 'EntitlementOverride', kind: 'async_delete', via: 'subjectId' },
      { to: 'QuotaCounter', kind: 'async_delete', via: 'subjectId' },
      { to: 'LifecycleExport', kind: 'deep', via: 'subjectId' },
      { to: 'ConsentAcceptance', kind: 'shallow', via: 'subjectId' },
      { to: 'RelationTuple', kind: 'async_delete', via: 'subjectId' },
      { to: 'PlatformStaff', kind: 'deep', via: 'userId' },
      { to: 'FinAuditLog', kind: 'shallow', via: 'userId' },
      { to: 'SecurityEvent', kind: 'shallow', via: 'subjectUserId' },
      { to: 'VerifyChallenge', kind: 'async_delete', via: 'userId' },
      { to: 'ChatterEntry', kind: 'async_nullify', via: 'actorId' },
      { to: 'NotificationEvent', kind: 'async_nullify', via: 'actorId' },
      { to: 'SearchDocument', kind: 'async_delete', via: 'authorId' },
      { to: 'Currency', kind: 'shallow', via: 'issuerId' },
      { to: 'table:analytics.events', kind: 'async_delete', via: 'user_id' },
      { to: 'table:idem.keys', kind: 'async_delete', via: 'user_id' },
      { to: 'table:idem.responses', kind: 'shallow', via: 'scope_id' },
    ],
    enforcement: notEnforced('tombstone row keeps references intact; personal data is scrubbed by the erasure orchestrator'),
    holdAware: true,
    proofEvent: 'account.anonymized',
    exportable: 'user',
    // Строка аккаунта — сам человек; реквизиты («для договоров») — глазами самого (ЗоПД ст. 24)
    exportScope: { user: { columns: ['id'] } },
    exportGuard: [
      guard('staff.member', { iin: 'iin', residentialAddress: 'residentialAddress', idDocNumber: 'idDocNumber', idDocIssuedBy: 'idDocIssuedBy', idDocIssuedAt: 'idDocIssuedAt' }, { subject: 'id' }),
      guard('user.card', { phone: 'phone', email: 'email', dateOfBirth: 'birthYear' }, { subject: 'id' }),
    ],
  },
  UserRole: {
    owner: 'core/roles',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('role directory: resolved on every request before the cell'),
    subjects: [subject('userId', 'member'), subject('grantedBy', 'actor')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: eraseHook('users.account'),
    onTenantPurge: tenantBatched('tenantId'),
    edges: [],
    enforcement: CASCADE,
    holdAware: false,
  },
  Session: {
    owner: 'core/users',
    version: 1,
    dataClass: 'auth_secret',
    ownerKey: global('sessions are verified before the cell is known'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONTRACT,
    retention: forDays(90, 'event:revoked'),
    onSubjectErasure: eraseHook('users.account'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('revokedAt'),
    extraRules: [{ filter: {}, days: 90, column: 'expiresAt' }],
    holdAware: false,
  },
  UserDevice: {
    owner: 'core/audit',
    version: 1,
    dataClass: 'identity_pii',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: interest('account security: recognise new devices'),
    retention: forDays(400, 'lastActivity'),
    onSubjectErasure: eraseHook('users.account'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('lastSeenAt'),
    // Забытое устройство (человек «забыл» его сам или год без входа) — год после отметки
    extraRules: [{ filter: {}, days: 365, column: 'forgottenAt' }],
    holdAware: false,
    exportable: 'user',
  },
  VerifyChallenge: {
    owner: 'core/verify',
    version: 1,
    dataClass: 'auth_secret',
    ownerKey: global('one-time codes are issued before sign-in (phone, not user)'),
    subjects: [subject('userId', 'owner')],
    legalBasis: interest('fraud prevention: audit of one-time code chains'),
    retention: forDays(7),
    onSubjectErasure: eraseBy('userId'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('createdAt'),
    holdAware: false,
  },
  RelationTuple: {
    owner: 'core/access',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('access graph edges span owners; projections are rebuilt from domain rows'),
    subjects: [subject('subjectId', 'member')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: eraseHook('access.subject'),
    onTenantPurge: tenantHook('access.tuples'),
    edges: [],
    enforcement: CASCADE,
    holdAware: false,
  },

  // ================= Уведомления =================
  NotificationEvent: {
    owner: 'core/notifications',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: scoped('workspaceId'),
    subjects: [subject('actorId', 'actor')],
    // Имена людей в payload (парой с id): «о ком» событие — стирание переписывает и их
    personIds: { fn: 'notification_person_ids', args: ['payload'], keys: NOTIFICATION_PERSON_ID_KEYS },
    legalBasis: CONTRACT,
    retention: forDays(90),
    // Снимок актора «переживал удаление» — утечка имени: при стирании актора переписывается
    onSubjectErasure: pseudonymizeHook('notifications.subject', 'snapshot'),
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [deep('NotificationDelivery', 'eventId'), deep('Notification', 'eventId')],
    enforcement: batched('createdAt', undefined, 'notifications.events'),
    holdAware: true,
  },
  Notification: {
    owner: 'core/notifications',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'recipient')],
    legalBasis: CONTRACT,
    retention: forDays(90),
    onSubjectErasure: eraseBy('userId'),
    // Строки с контекстом удалённой организации — общей пачкой по workspaceId (индекс есть):
    // их диплинки ведут в несуществующее, «архив» оставил бы призрака в бейдже
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [],
    // Исключения «сохранено» / «отложено» несовместимы со сбросом партиции — строки батчами
    enforcement: batched('createdAt', { savedAt: [null] }, 'notifications.rows'),
    holdAware: true,
    exportable: 'user',
  },
  NotificationDelivery: {
    owner: 'core/notifications',
    version: 1,
    dataClass: 'operational',
    ownerKey: via('user', 'NotificationEvent'),
    subjects: [subject('userId', 'recipient')],
    legalBasis: interest('delivery diagnostics'),
    retention: forDays(30),
    onSubjectErasure: noSubject('delivery log expires with its 30-day partition — inside the erasure window'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: dropPartition('createdAt', 'month'),
    holdAware: false,
  },
  NotificationPreference: {
    owner: 'core/notifications',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: eraseBy('userId'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('settings live while the account lives'),
    holdAware: true,
    exportable: 'user',
  },
  WorkspaceNotificationPolicy: {
    owner: 'core/notifications',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('updatedBy', 'actor')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  NotificationSubscription: {
    owner: 'core/notifications',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: eraseBy('userId'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  NotificationDevice: {
    owner: 'core/notifications',
    version: 1,
    dataClass: 'auth_secret',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONTRACT,
    retention: forDays(270, 'lastActivity'),
    onSubjectErasure: eraseBy('userId'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('lastSeenAt'),
    holdAware: false,
  },
  UserNotificationSettings: {
    owner: 'core/notifications',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: eraseBy('userId'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('settings live while the account lives'),
    holdAware: true,
    exportable: 'user',
  },

  // ================= Файлы, голос, звонки =================
  FileObject: {
    owner: 'core/files',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: polymorphic(['user', 'workspace']),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONSENT,
    // Удалённый файл живёт 7 суток (восстановление по ссылке), затем байты и строка уходят
    retention: forDays(7, 'event:revoked'),
    onSubjectErasure: eraseHook('files.subject', true),
    onTenantPurge: tenantHook('files.owned'),
    edges: [
      deep('DriveNodeVersion', 'fileId'),
      deep('DriveNode', 'fileId'),
      deep('FileLink', 'fileId'),
      deep('FileVariant', 'fileId'),
      deep('VoiceTranscript', 'fileId'),
      // Байты каждого профиля уходят вместе со строкой файла
      ...Object.keys(BLOB_LIFECYCLE).map((to) => deep(to, 'storageKey')),
    ],
    enforcement: batched('deletedAt', undefined, 'files.deleted'),
    holdAware: true,
    exportable: 'both',
  },
  FileLink: {
    owner: 'core/files',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'FileObject'),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    // Файл живёт, пока на него есть хоть одно место (Facebook 2018: видео удалили вместе с копией)
    edges: [{ to: 'FileObject', kind: 'refcount', via: 'fileId' }],
    enforcement: CASCADE,
    holdAware: true,
  },
  FileVariant: {
    owner: 'core/files',
    version: 1,
    dataClass: 'derived',
    ownerKey: via('user', 'FileObject'),
    subjects: [],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('derived rendition of the parent file'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: false,
  },
  VoiceTranscript: {
    owner: 'core/voice',
    version: 1,
    dataClass: 'derived',
    ownerKey: via('user', 'FileObject'),
    subjects: [subject('requestedById', 'actor')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('follows its file: erasing the owner\'s file takes the transcript'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  CallSession: {
    owner: 'core/calls',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: scoped('workspaceId'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: forDays(180),
    onSubjectErasure: noSubject('participants live in CallSessionParticipant'),
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [deep('CallRecording', 'sessionId'), deep('CallSessionParticipant', 'sessionId')],
    // Срок один для рабочих и личных звонков: у личных нет организации, каскад их не заберёт
    enforcement: batched('updatedAt', { status: ['ended'] }),
    holdAware: true,
  },
  CallSessionParticipant: {
    owner: 'core/calls',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: via('conversation', 'CallSession'),
    subjects: [subject('userId', 'participant')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: eraseBy('userId'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  CallRecording: {
    owner: 'core/calls',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: via('conversation', 'CallSession'),
    subjects: [],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('the recording file follows its FileObject; claims are per person'),
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [deep('CallRecordingClaim', 'recordingId'), { to: 'FileObject', kind: 'refcount', via: 'fileId' }],
    enforcement: CASCADE,
    holdAware: true,
  },
  CallRecordingClaim: {
    owner: 'core/calls',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: eraseBy('userId'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },

  // ================= Джобы, хроника, поиск =================
  Job: {
    owner: 'core/jobs',
    version: 2,
    dataClass: 'operational',
    ownerKey: global('queue is platform infrastructure; payloads carry ids only'),
    subjects: [],
    legalBasis: interest('background work that must happen'),
    // Терминальные строки: выполненные — сутки, похороненные и отменённые — 30 дней (River / Solid Queue prune)
    retention: forDays(1, 'event:terminal'),
    onSubjectErasure: noSubject('payloads carry ids only, never personal text'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    // Срок — от момента, когда джоб стал терминальным (finished_at; частичный jobs_retention_idx)
    enforcement: batched('finishedAt', { status: ['completed'] }, 'jobs.terminal'),
    extraRules: [{ filter: { status: ['discarded', 'cancelled'] }, days: 30 }],
    holdAware: false,
  },
  ChatterEntry: {
    owner: 'core/chatter',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: scoped('workspaceId'),
    subjects: [subject('actorId', 'actor')],
    // Имена людей в payload и изменениях (цель записи, заместитель, ответственный «было → стало»)
    personIds: { fn: 'chatter_person_ids', args: ['payload', 'changes'], keys: [...CHATTER_PERSON_ID_KEYS, ...CHANGE_PERSON_ID_KEYS] },
    legalBasis: CONTRACT,
    // Живёт с сущностью; у организации — срок в коридоре её политики (чтение режет старше)
    retention: { trigger: 'created', defaultDays: FOREVER, floorDays: 1, tenantConfigurable: true, entitlementKey: 'lifecycle.retention.tenant_record.ceilingDays' },
    onSubjectErasure: pseudonymizeHook('chatter.subject', 'actorName'),
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [],
    // Срок выбирает организация (коридор) — общий раннер режет её строки по workspaceId
    enforcement: batched('createdAt'),
    holdAware: true,
    exportable: 'both',
  },
  SearchDocument: {
    owner: 'core/search',
    version: 1,
    dataClass: 'derived',
    ownerKey: scoped('workspaceId', 'authorId', 'chatId'),
    subjects: [subject('authorId', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('a projection follows its source row (loose FK, owner purge); shared messages stay searchable for the other side'),
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [],
    enforcement: CASCADE,
    holdAware: false,
  },

  // ================= Ссылки наружу, решения, подпись, офисные документы =================
  ShareLink: {
    owner: 'core/share-links',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: polymorphic(['user', 'workspace']),
    subjects: [subject('createdById', 'author'), subject('revokedById', 'actor')],
    legalBasis: CONSENT,
    retention: forDays(365, 'event:revoked'),
    onSubjectErasure: noSubject('a link follows the resource it opens; creator and revoker are references (tombstone)'),
    onTenantPurge: tenantHook('share-links.workspace'),
    edges: [deep('ShareLinkVisit', 'linkId')],
    enforcement: batched('revokedAt'),
    holdAware: true,
  },
  ShareLinkVisit: {
    owner: 'core/share-links',
    version: 1,
    dataClass: 'operational',
    ownerKey: via('user', 'ShareLink'),
    subjects: [subject('guestId', 'guest')],
    legalBasis: interest('who opened a shared object: owner-visible access log'),
    retention: forDays(365),
    onSubjectErasure: noSubject('guests are not accounts: their visits follow the link'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: batched('openedAt'),
    holdAware: false,
  },
  ShareLinkGuest: {
    owner: 'core/share-links',
    version: 1,
    dataClass: 'identity_pii',
    ownerKey: polymorphic(['user', 'workspace']),
    subjects: [subject('id', 'guest')],
    legalBasis: CONSENT,
    retention: forDays(365, 'lastActivity'),
    onSubjectErasure: shred('user'),
    onTenantPurge: tenantHook('share-links.workspace'),
    edges: [shallow('ShareLinkVisit', 'guestId')],
    enforcement: batched('lastVerifiedAt'),
    holdAware: true,
  },
  ApprovalRequest: {
    owner: 'core/approvals',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: scoped('workspaceId', 'createdById'),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: tenantHook('approvals.workspace'),
    edges: [deep('ApprovalStep', 'requestId')],
    enforcement: notEnforced('decision records live with the subject record'),
    holdAware: true,
    exportable: 'workspace',
  },
  ApprovalStep: {
    owner: 'core/approvals',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: via('workspace', 'ApprovalRequest'),
    subjects: [subject('assigneeId', 'recipient')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: pseudonymizeBy(['assigneeId'], 'assigneeLabelName', 'assigneeLabel'),
    onTenantPurge: CASCADE_FK,
    edges: [deep('ApprovalDecision', 'stepId')],
    enforcement: CASCADE,
    holdAware: true,
  },
  ApprovalDecision: {
    owner: 'core/approvals',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: via('workspace', 'ApprovalStep'),
    subjects: [subject('userId', 'actor')],
    legalBasis: law('kz_digital_code_art62'),
    retention: withParent,
    onSubjectErasure: retainLegal('kz_digital_code_art62', FOREVER),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  SignRequest: {
    owner: 'core/sign',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: scoped('workspaceId', 'createdById'),
    subjects: [subject('createdById', 'author')],
    legalBasis: law('kz_digital_code_art62'),
    retention: legalFloor(FOREVER, 'created'),
    onSubjectErasure: retainLegal('kz_digital_code_art62', FOREVER),
    // Доказательства подписи живут дальше; подпись В ОЖИДАНИИ отменяется шагом модуля
    onTenantPurge: tenantRetain('kz_digital_code_art62', FOREVER, 'sign.workspace'),
    edges: [deep('SignAct', 'requestId')],
    enforcement: notEnforced('signature evidence is kept for the life of the signed document'),
    holdAware: true,
  },
  SignAct: {
    owner: 'core/sign',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: via('workspace', 'SignRequest'),
    subjects: [subject('signerUserId', 'actor'), subject('signerGuestId', 'guest')],
    legalBasis: law('kz_digital_code_art62'),
    retention: legalFloor(FOREVER, 'parent'),
    onSubjectErasure: retainLegal('kz_digital_code_art62', FOREVER),
    onTenantPurge: tenantRetain('kz_digital_code_art62', FOREVER),
    edges: [deep('SignActEvent', 'actId'), deep('SignQrSession', 'actId')],
    enforcement: notEnforced('signature evidence is eternal (the act is the proof)'),
    holdAware: true,
  },
  SignActEvent: {
    owner: 'core/sign',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: via('workspace', 'SignAct'),
    subjects: [],
    legalBasis: law('kz_digital_code_art62'),
    retention: legalFloor(FOREVER, 'parent'),
    onSubjectErasure: noSubject('protocol events carry codes, the person lives in SignAct'),
    onTenantPurge: tenantRetain('kz_digital_code_art62', FOREVER),
    edges: [],
    enforcement: notEnforced('signature protocol is eternal'),
    holdAware: true,
  },
  SignQrSession: {
    owner: 'core/sign',
    version: 1,
    dataClass: 'ephemeral',
    ownerKey: via('workspace', 'SignAct'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: forDays(1, 'event:expired'),
    onSubjectErasure: noSubject('one-time QR session'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: batched('expiresAt'),
    holdAware: false,
  },
  Document: {
    owner: 'core/docs',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: polymorphic(['user', 'workspace']),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: eraseHook('docs.subject', true),
    onTenantPurge: tenantHook('docs.owned'),
    edges: [deep('DocumentSession', 'documentId'), deep('DocumentVersion', 'documentId'), { to: 'FileObject', kind: 'refcount', via: 'fileId' }],
    enforcement: batched('deletedAt', undefined, 'docs.trash'),
    holdAware: true,
    rootEntity: true,
    exportable: 'both',
  },
  DocumentVersion: {
    owner: 'core/docs',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'Document'),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [{ to: 'FileObject', kind: 'refcount', via: 'fileId' }],
    enforcement: CASCADE,
    holdAware: true,
  },
  DocumentSession: {
    owner: 'core/docs',
    version: 1,
    dataClass: 'ephemeral',
    ownerKey: via('user', 'Document'),
    subjects: [subject('participantIds', 'participant')],
    legalBasis: CONTRACT,
    retention: forDays(1, 'event:expired'),
    onSubjectErasure: noSubject('ephemeral editing sessions expire on their own'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: batched('expiresAt'),
    holdAware: false,
  },

  // ================= Тарифы =================
  Plan: {
    owner: 'core/entitlements',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('platform catalogue'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: noSubject('catalogue, no personal data'),
    onTenantPurge: NOT_TENANT,
    edges: [deep('PlanVersion', 'planId')],
    enforcement: notEnforced('versioned catalogue is kept for billing history'),
    holdAware: false,
  },
  PlanVersion: {
    owner: 'core/entitlements',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('platform catalogue'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: noSubject('catalogue, no personal data'),
    onTenantPurge: NOT_TENANT,
    edges: [deep('SubjectSubscription', 'planVersionId')],
    enforcement: notEnforced('versioned catalogue is kept for billing history'),
    holdAware: false,
  },
  SubjectSubscription: {
    owner: 'core/entitlements',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: polymorphic(['user', 'workspace'], 'subjectType', 'subjectId'),
    subjects: [subject('subjectId', 'owner'), subject('createdBy', 'actor')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: eraseHook('users.account'),
    onTenantPurge: tenantHook('entitlements.subject'),
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  EntitlementGrant: {
    owner: 'core/entitlements',
    version: 1,
    dataClass: 'operational',
    ownerKey: polymorphic(['user', 'workspace'], 'subjectType', 'subjectId'),
    subjects: [subject('subjectId', 'owner'), subject('grantedBy', 'actor')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: eraseHook('users.account'),
    onTenantPurge: tenantHook('entitlements.subject'),
    edges: [],
    enforcement: CASCADE,
    holdAware: false,
  },
  EntitlementOverride: {
    owner: 'core/entitlements',
    version: 1,
    dataClass: 'operational',
    ownerKey: polymorphic(['user', 'workspace'], 'subjectType', 'subjectId'),
    subjects: [subject('subjectId', 'owner'), subject('createdBy', 'actor')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: eraseHook('users.account'),
    onTenantPurge: tenantHook('entitlements.subject'),
    edges: [],
    enforcement: CASCADE,
    holdAware: false,
  },
  QuotaCounter: {
    owner: 'core/entitlements',
    version: 1,
    dataClass: 'operational',
    ownerKey: polymorphic(['user', 'workspace'], 'subjectType', 'subjectId'),
    subjects: [subject('subjectId', 'owner')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: eraseHook('users.account'),
    onTenantPurge: tenantHook('entitlements.subject'),
    edges: [],
    enforcement: CASCADE,
    holdAware: false,
  },

  // ================= Кабинет платформы =================
  PlatformStaff: {
    owner: 'core/platform',
    version: 1,
    dataClass: 'security_audit',
    ownerKey: global('platform staff directory'),
    subjects: [subject('userId', 'employee'), subject('createdBy', 'actor')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: retainLegal('kz_et832_p38', YEARS(3)),
    onTenantPurge: NOT_TENANT,
    edges: [deep('PlatformStaffRole', 'userId')],
    enforcement: notEnforced('staff record is kept while privileged actions reference it'),
    holdAware: true,
  },
  PlatformStaffRole: {
    owner: 'core/platform',
    version: 1,
    dataClass: 'security_audit',
    ownerKey: global('platform staff directory'),
    subjects: [subject('userId', 'employee'), subject('grantedBy', 'actor')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: retainLegal('kz_et832_p38', YEARS(3)),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  PlatformSession: {
    owner: 'core/platform',
    version: 1,
    dataClass: 'auth_secret',
    ownerKey: global('console sessions'),
    subjects: [subject('userId', 'employee')],
    legalBasis: CONTRACT,
    retention: forDays(1, 'event:expired'),
    onSubjectErasure: eraseBy('userId'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('expiresAt'),
    // Отозванная раньше срока (выход, «четыре глаза», блокировка сотрудника) — сутки после отзыва
    extraRules: [{ filter: {}, days: 1, column: 'revokedAt' }],
    holdAware: false,
  },
  PlatformPolicy: {
    owner: 'core/platform',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('platform-wide settings'),
    subjects: [subject('updatedBy', 'actor')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('single settings row'),
    holdAware: false,
  },
  PlatformCommandRequest: {
    owner: 'core/platform',
    version: 1,
    dataClass: 'security_audit',
    ownerKey: global('four-eyes requests of platform staff'),
    subjects: [subject('actorId', 'actor'), subject('decidedBy', 'actor')],
    legalBasis: law('kz_et832_p38'),
    retention: legalFloor(YEARS(3), 'created'),
    onSubjectErasure: retainLegal('kz_et832_p38', YEARS(3)),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('createdAt'),
    holdAware: true,
  },
  PlatformCommandReceipt: {
    owner: 'core/audit',
    version: 1,
    dataClass: 'security_audit',
    ownerKey: global('idempotency receipts of platform commands (append-only)'),
    subjects: [subject('actorId', 'actor')],
    legalBasis: law('kz_et832_p38'),
    retention: legalFloor(YEARS(3), 'created'),
    onSubjectErasure: retainLegal('kz_et832_p38', YEARS(3)),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('append-only; dropped with its audit partition window by the owner role'),
    holdAware: true,
  },

  // ================= Аналитика =================
  AnalyticsIdentityLink: {
    owner: 'core/analytics',
    version: 1,
    dataClass: 'analytics_event',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONSENT,
    retention: forDays(400),
    onSubjectErasure: eraseHook('analytics.subject'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('linkedAt'),
    holdAware: false,
  },
  AnalyticsEventOverride: {
    owner: 'core/analytics',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('registry overrides'),
    subjects: [],
    legalBasis: interest('product analytics configuration'),
    retention: keep(),
    onSubjectErasure: noSubject('configuration, no personal data'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('configuration row'),
    holdAware: false,
  },
  AnalyticsQuarantine: {
    owner: 'core/analytics',
    version: 1,
    dataClass: 'analytics_event',
    ownerKey: global('rejected raw events awaiting triage'),
    subjects: [],
    legalBasis: interest('ingest data quality'),
    retention: forDays(30, 'lastActivity'),
    onSubjectErasure: noSubject('quarantined rows carry no identity (dropped on intake)'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('lastSeenAt'),
    holdAware: false,
  },
  AnalyticsRollupEventDay: {
    owner: 'core/analytics',
    version: 1,
    dataClass: 'derived',
    ownerKey: global('aggregates; workspace dimension is erased on purge'),
    subjects: [],
    legalBasis: interest('product analytics aggregates'),
    retention: keep(),
    onSubjectErasure: noSubject('no person dimension'),
    onTenantPurge: tenantHook('analytics.workspace'),
    edges: [],
    enforcement: notEnforced('aggregates are kept (no personal data)'),
    holdAware: false,
  },
  AnalyticsRollupActorDay: {
    owner: 'core/analytics',
    version: 1,
    dataClass: 'derived',
    ownerKey: byUser('actorId'),
    subjects: [subject('actorId', 'actor')],
    legalBasis: CONSENT,
    retention: forDays(400),
    onSubjectErasure: eraseHook('analytics.subject'),
    onTenantPurge: tenantHook('analytics.workspace'),
    edges: [],
    // Срок — как у сырья (`ANALYTICS_RAW_RETENTION_DAYS`, умолчание = реестр): шаг модуля, не общая пачка
    enforcement: batched('day', undefined, 'analytics.actor-days'),
    holdAware: false,
  },
  AnalyticsRollupSessionDay: {
    owner: 'core/analytics',
    version: 1,
    dataClass: 'derived',
    ownerKey: global('aggregates; workspace dimension is erased on purge'),
    subjects: [],
    legalBasis: interest('product analytics aggregates'),
    retention: keep(),
    onSubjectErasure: noSubject('no person dimension'),
    onTenantPurge: tenantHook('analytics.workspace'),
    edges: [],
    enforcement: notEnforced('aggregates are kept (no personal data)'),
    holdAware: false,
  },
  AnalyticsReport: {
    owner: 'core/analytics',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('platform console reports'),
    subjects: [subject('createdBy', 'author')],
    legalBasis: interest('product analytics configuration'),
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('saved report definitions'),
    holdAware: false,
  },
  AnalyticsDashboard: {
    owner: 'core/analytics',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('platform console dashboards'),
    subjects: [subject('createdBy', 'author')],
    legalBasis: interest('product analytics configuration'),
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('saved dashboard definitions'),
    holdAware: false,
  },

  // ================= Ключи, боты, вебхуки =================
  CryptoKey: {
    owner: 'core/keys',
    version: 1,
    dataClass: 'auth_secret',
    ownerKey: global('keystore: a scope is destroyed by crypto-shredding, not by row deletion'),
    subjects: [],
    legalBasis: interest('encryption of personal data'),
    retention: keep(),
    onSubjectErasure: noSubject('key scope of the person is destroyed by KeysCascades'),
    onTenantPurge: NOT_TENANT,
    edges: [deep('CryptoKeyVersion', 'keyId')],
    enforcement: notEnforced('key material lifecycle is owned by core/keys rotations and destruction'),
    holdAware: false,
  },
  CryptoKeyVersion: {
    owner: 'core/keys',
    version: 1,
    dataClass: 'auth_secret',
    ownerKey: global('keystore'),
    subjects: [],
    legalBasis: interest('encryption of personal data'),
    retention: withParent,
    onSubjectErasure: noSubject('destroyed with its scope (crypto-shredding)'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: CASCADE,
    holdAware: false,
  },
  Bot: {
    owner: 'core/keys',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: tenantHook('keys.workspace'),
    edges: [deep('ApiKey', 'botId')],
    enforcement: CASCADE,
    holdAware: true,
  },
  ApiKey: {
    owner: 'core/keys',
    version: 1,
    dataClass: 'auth_secret',
    ownerKey: scoped('workspaceId', 'userId'),
    subjects: [subject('userId', 'owner'), subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: forDays(90, 'event:revoked'),
    onSubjectErasure: eraseHook('keys.subject', true),
    onTenantPurge: tenantHook('keys.workspace'),
    edges: [],
    enforcement: batched('revokedAt'),
    holdAware: false,
  },
  ApiAccessLog: {
    owner: 'core/keys',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('access log of API keys (partitioned by time)'),
    subjects: [],
    legalBasis: interest('security of integrations'),
    // Организация журнал обращений не видит — её выбор срока здесь ничего бы не значил: срок единый
    retention: { trigger: 'created', defaultDays: 90, floorDays: 30 },
    onSubjectErasure: noSubject('rows carry key ids and codes; the key owner is erased via ApiKey'),
    onTenantPurge: tenantRetain('kz_et832_p38', 90),
    edges: [],
    enforcement: dropPartition('at', 'month'),
    holdAware: false,
  },
  WebhookEndpoint: {
    owner: 'core/webhooks',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [deep('WebhookDelivery', 'endpointId')],
    enforcement: CASCADE,
    holdAware: true,
  },
  WebhookDelivery: {
    owner: 'core/webhooks',
    version: 1,
    dataClass: 'operational',
    ownerKey: via('workspace', 'WebhookEndpoint'),
    subjects: [],
    legalBasis: CONTRACT,
    // 30 дней (Stripe); после 7 дней тело заменяется хешем — минимизация ПДн в копии.
    // Потолок = умолчание: организация может только СОКРАЩАТЬ (лист партиции уходит целиком на
    // 30-й день — выбор длиннее одной организации держал бы доставки всех остальных)
    retention: { trigger: 'created', defaultDays: 30, floorDays: 7, ceilingDays: 30, tenantConfigurable: true, entitlementKey: 'lifecycle.retention.operational.ceilingDays' },
    onSubjectErasure: noSubject('bodies become a hash after 7 days — inside the erasure window'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    tiers: [
      { tier: 'hot', minAgeDays: 0 },
      { tier: 'warm', minAgeDays: 7 },
    ],
    enforcement: dropPartition('createdAt', 'month'),
    holdAware: false,
  },
  WorkspaceKeyPolicy: {
    owner: 'core/keys',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('settings row of the organisation'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },

  // ================= Согласия, инциденты ПДн =================
  ConsentVersion: {
    owner: 'core/consents',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: global('platform legal documents'),
    subjects: [subject('createdById', 'author')],
    legalBasis: law('kz_pd_law_consent_evidence'),
    retention: legalFloor(FOREVER, 'created'),
    onSubjectErasure: retainLegal('kz_pd_law_consent_evidence', FOREVER),
    onTenantPurge: NOT_TENANT,
    edges: [deep('ConsentAcceptance', 'versionId')],
    enforcement: notEnforced('published legal texts are evidence forever'),
    holdAware: true,
  },
  ConsentAcceptance: {
    owner: 'core/consents',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: polymorphic(['user', 'workspace'], 'subjectType', 'subjectId'),
    subjects: [subject('subjectId', 'owner'), subject('actorUserId', 'actor')],
    legalBasis: law('kz_pd_law_consent_evidence'),
    retention: legalFloor(FOREVER, 'created'),
    // Приёмка — доказательство: переживает и человека, и организацию (номер в ней зашифрован)
    onSubjectErasure: retainLegal('kz_pd_law_consent_evidence', FOREVER),
    onTenantPurge: tenantRetain('kz_pd_law_consent_evidence', FOREVER),
    edges: [],
    enforcement: notEnforced('acceptance records are evidence forever'),
    holdAware: true,
    exportable: 'both',
  },
  PdIncident: {
    owner: 'core/consents',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: global('platform incident register'),
    subjects: [subject('actorUserId', 'actor')],
    legalBasis: law('kz_pd_incident_rules'),
    retention: legalFloor(FOREVER, 'created'),
    onSubjectErasure: retainLegal('kz_pd_incident_rules', FOREVER),
    onTenantPurge: NOT_TENANT,
    edges: [deep('PdIncidentEvent', 'incidentId')],
    enforcement: notEnforced('incident register is kept forever'),
    holdAware: true,
  },
  PdIncidentEvent: {
    owner: 'core/consents',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: global('platform incident register'),
    subjects: [subject('actorUserId', 'actor')],
    legalBasis: law('kz_pd_incident_rules'),
    retention: legalFloor(FOREVER, 'parent'),
    onSubjectErasure: retainLegal('kz_pd_incident_rules', FOREVER),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('incident register is kept forever'),
    holdAware: true,
  },

  // ================= Идемпотентность, журнал безопасности =================
  IdempotencyInbox: {
    owner: 'core/idempotency',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('exactly-once inbox of foreign events'),
    subjects: [],
    legalBasis: interest('exactly-once processing of incoming events'),
    retention: forDays(30),
    onSubjectErasure: noSubject('inbox rows carry foreign event ids only'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('receivedAt', undefined, 'idempotency.inbox'),
    holdAware: false,
  },
  SecurityEvent: {
    owner: 'core/audit',
    version: 1,
    dataClass: 'security_audit',
    ownerKey: global('append-only security log with three viewers'),
    subjects: [subject('actorId', 'actor'), subject('subjectUserId', 'owner')],
    legalBasis: law('kz_et832_p38'),
    retention: legalFloor(YEARS(3), 'created'),
    // Журнал переживает человека (срок по закону); ПДн в нём — шифротекст под KEK, IP — под платформенным KEK
    onSubjectErasure: retainLegal('kz_et832_p38', YEARS(3)),
    onTenantPurge: tenantRetain('kz_et832_p38', YEARS(3)),
    edges: [],
    tiers: [
      { tier: 'hot', minAgeDays: 0 },
      { tier: 'cold', minAgeDays: 62, waitForArchive: true },
    ],
    enforcement: dropPartition('occurredAt', 'month'),
    holdAware: true,
    exportable: 'both',
  },
  SecurityDigest: {
    owner: 'core/audit',
    version: 1,
    dataClass: 'security_audit',
    ownerKey: global('integrity digests of the security log'),
    subjects: [],
    legalBasis: law('kz_et832_p38'),
    retention: legalFloor(FOREVER, 'created'),
    onSubjectErasure: noSubject('hashes only'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('integrity chain is kept forever (hashes only)'),
    holdAware: true,
  },
  SecurityPartitionArchive: {
    owner: 'core/audit',
    version: 1,
    dataClass: 'security_audit',
    ownerKey: global('manifests of archived security log partitions'),
    subjects: [],
    legalBasis: law('kz_et832_p38'),
    retention: legalFloor(FOREVER, 'created'),
    onSubjectErasure: noSubject('manifests carry counts and hashes'),
    onTenantPurge: NOT_TENANT,
    edges: [{ to: 'derived:audit_archive', kind: 'deep', via: 'partition' }],
    enforcement: notEnforced('archive manifests are kept forever'),
    holdAware: true,
  },
  SecurityAlert: {
    owner: 'core/audit',
    version: 1,
    dataClass: 'security_audit',
    ownerKey: global('platform security alerts'),
    subjects: [subject('subjectUserId', 'owner'), subject('assigneeId', 'employee')],
    legalBasis: law('kz_et832_p38'),
    retention: legalFloor(YEARS(3), 'created'),
    onSubjectErasure: retainLegal('kz_et832_p38', YEARS(3)),
    onTenantPurge: tenantRetain('kz_et832_p38', YEARS(3)),
    edges: [],
    enforcement: batched('updatedAt', { status: ['closed'] }),
    holdAware: true,
  },

  // ================= Видимость полей =================
  VisibilityPolicy: {
    owner: 'core/visibility',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: polymorphic(['user', 'workspace']),
    subjects: [subject('ownerId', 'owner'), subject('createdById', 'actor')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: eraseHook('users.account'),
    onTenantPurge: tenantHook('visibility.owner'),
    edges: [deep('VisibilityRule', 'policyId')],
    enforcement: notEnforced('settings live while the owner lives'),
    holdAware: true,
  },
  VisibilityRule: {
    owner: 'core/visibility',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'VisibilityPolicy'),
    subjects: [],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('rules die with their policy (cascade)'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  WorkspaceVisibilitySettings: {
    owner: 'core/visibility',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('updatedById', 'actor')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },

  // ================= Жизненный цикл данных (сам движок) =================
  LifecycleSetting: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('changedById', 'actor')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  LifecycleHold: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'legal_record',
    // Заморозка переживает организацию (FK нет): это след юридического процесса
    ownerKey: global('legal holds: the trace of a legal process outlives the organisation'),
    subjects: [subject('custodianUserId', 'owner'), subject('createdById', 'actor'), subject('releasedById', 'actor')],
    legalBasis: interest('evidence that deletion was suspended for a legal process'),
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('append-only trace of a legal process (the trigger forbids delete)'),
    holdAware: true,
  },
  LifecycleHoldStore: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: global('rows preserved under a legal hold (sealed envelope under the owner KEK)'),
    subjects: [],
    legalBasis: interest('rows preserved for a legal process'),
    // Живёт, пока жива заморозка: снятие → строки уходят
    retention: forDays(1, 'event:revoked'),
    onSubjectErasure: noSubject('a sealed envelope of a held row: erasure waits for the hold release'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('extractedAt', undefined, 'lifecycle.hold-store'),
    holdAware: true,
  },
  LifecycleHoldExtraction: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: global('markers «held rows of this partition were extracted»'),
    subjects: [],
    legalBasis: interest('rows preserved for a legal process'),
    retention: forDays(1, 'event:revoked'),
    onSubjectErasure: noSubject('hold id, partition name and a counter'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('extractedAt', undefined, 'lifecycle.hold-store'),
    holdAware: true,
  },
  LifecycleErasureRequest: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: global('erasure requests: the proof that a person or an organisation was erased'),
    // Кому сообщить о завершении стирания организации — ссылка на человека (стирание её не ведёт)
    subjects: [subject('subjectId', 'owner'), subject('notifyUserId', 'actor')],
    legalBasis: law('kz_pd_law_art8_7'),
    retention: legalFloor(YEARS(3), 'event:terminal'),
    onSubjectErasure: noSubject('the request is the proof of erasure: subject id and pseudonym only'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('completedAt', { status: ['completed', 'cancelled', 'failed'] }),
    holdAware: true,
  },
  LifecycleErasureJournal: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: global('journal of erasures replayed after any restore'),
    subjects: [],
    legalBasis: law('kz_pd_law_art8_7'),
    retention: legalFloor(FOREVER, 'created'),
    onSubjectErasure: noSubject('pseudonyms, policy versions, counters and key ids only'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('append-only: the journal must outlive every backup it has to correct'),
    holdAware: true,
  },
  LifecycleExport: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: polymorphic(['user', 'workspace'], 'subjectType', 'subjectId'),
    subjects: [subject('subjectId', 'owner'), subject('requestedById', 'actor')],
    legalBasis: law('kz_pd_law_art12'),
    // Архив живёт 7 дней (derived:lifecycle_exports); строка задания — месяц (история «Мои данные»)
    retention: forDays(30),
    onSubjectErasure: eraseHook('lifecycle.exports'),
    onTenantPurge: tenantHook('lifecycle.exports'),
    edges: [{ to: 'derived:lifecycle_exports', kind: 'deep', via: 'id' }],
    enforcement: batched('createdAt', undefined, 'lifecycle.exports'),
    holdAware: true,
  },
  LifecycleDeletedRow: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('queue of deleted parents for the loose-FK worker (row ids only)'),
    subjects: [],
    legalBasis: interest('delete the children of deleted rows that have no foreign keys'),
    // 7 дней после обработки; необработанная строка держит сброс своей партиции (функция владельца)
    retention: forDays(7, 'event:terminal'),
    onSubjectErasure: noSubject('row ids only'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: dropPartition('deletedAt', 'day'),
    holdAware: false,
  },
  LifecycleRun: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('enforcement runs: counters and reports (proof and dashboard)'),
    subjects: [],
    legalBasis: interest('proof that retention was enforced'),
    retention: forDays(400),
    onSubjectErasure: noSubject('counters and policy ids only'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('startedAt'),
    holdAware: false,
  },
  LifecycleBackupRun: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('reports of backups and restore drills'),
    subjects: [],
    legalBasis: interest('disaster recovery evidence'),
    retention: forDays(YEARS(2)),
    onSubjectErasure: noSubject('repository names, sizes and timings only'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('startedAt'),
    holdAware: false,
  },
  LifecycleStorageDaily: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('daily sizes of data classes (dashboard «Data»: growth over 90 days)'),
    subjects: [],
    legalBasis: interest('capacity planning of the platform'),
    retention: forDays(400),
    onSubjectErasure: noSubject('class codes, sizes and counts only'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('day'),
    holdAware: false,
  },
  LifecyclePolicyOverride: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('pause and retention of a policy set by a staff command'),
    subjects: [subject('changedById', 'actor')],
    legalBasis: interest('operating the retention runner'),
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('configuration: a row lives until the command clears it'),
    holdAware: false,
  },
  LifecyclePartitionSpec: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('rules of partitioned parents (written by migrations only)'),
    subjects: [],
    legalBasis: interest('retention floors enforced by the database'),
    retention: keep(),
    onSubjectErasure: noSubject('configuration'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('configuration written by migrations'),
    holdAware: false,
  },
  LifecyclePartitionArchive: {
    owner: 'core/lifecycle',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('manifests of archived log partitions'),
    subjects: [],
    legalBasis: interest('cold tier of logs kept past their hot window'),
    retention: keep(),
    onSubjectErasure: noSubject('manifests carry counts and hashes'),
    onTenantPurge: NOT_TENANT,
    edges: [{ to: 'derived:lifecycle_archive', kind: 'deep', via: 'partition' }],
    enforcement: notEnforced('a manifest lives while its archive object lives'),
    holdAware: false,
  },
} satisfies Record<string, LifecyclePolicyInput>;
