// Политики жизненного цикла ЛИЧНЫХ сервисов (и их B2B-половин в тех же таблицах): Окружение,
// Задачник, Календарь, Кошелёк-леджер и эскроу, Магазин и вишлист, скины карточек, Финансы,
// Диск, Заметки, Диктофон. Личный контент живёт, пока человек сам не удалит (корзина 30 дней);
// деньги — append-only и по закону о платежах, ПДн в них псевдонимизируются томбстоуном.
import {
  BY_REFERENCE,
  CASCADE,
  CASCADE_FK,
  CONSENT,
  CONTRACT,
  FOREVER,
  HARD_DELETE,
  HARD_DELETE_PERSONAL,
  NOT_TENANT,
  YEARS,
  batched,
  byUser,
  deep,
  forDays,
  global,
  keep,
  law,
  legalFloor,
  noSubject,
  notEnforced,
  polymorphic,
  retainLegal,
  scoped,
  shallow,
  subject,
  tenantBatched,
  tenantHook,
  tenantRetain,
  via,
  withParent,
} from './helpers';
import type { LifecyclePolicyInput } from './types';

export const PERSONAL_LIFECYCLE = {
  // ================= Окружение =================
  ContactLink: {
    owner: 'contacts',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: byUser('userAId'),
    subjects: [subject('userAId', 'member'), subject('userBId', 'member')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [deep('CircleMembership', 'contactLinkId')],
    enforcement: notEnforced('a link lives while both people keep it'),
    holdAware: true,
    exportable: 'user',
  },
  ContactInvitation: {
    owner: 'contacts',
    version: 1,
    dataClass: 'operational',
    ownerKey: byUser('fromUserId'),
    subjects: [subject('fromUserId', 'author'), subject('toUserId', 'recipient')],
    legalBasis: CONSENT,
    retention: forDays(30, 'event:expired'),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('expiresAt'),
    holdAware: false,
  },
  ContactBlock: {
    owner: 'contacts',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('blockerId'),
    subjects: [subject('blockerId', 'owner'), subject('blockedId', 'counterpart')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('a block lives until the person lifts it'),
    holdAware: true,
    exportable: 'user',
  },
  Circle: {
    owner: 'contacts',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('ownerId'),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [deep('CircleMembership', 'circleId'), shallow('Task', 'assignedCircleId')],
    enforcement: notEnforced('groups live until the owner deletes them'),
    holdAware: true,
    exportable: 'user',
  },
  CircleMembership: {
    owner: 'contacts',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'Circle'),
    subjects: [],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('the member is the contact link (erased with it)'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },

  // ================= Задачник =================
  Task: {
    owner: 'tasks',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: scoped('workspaceId', 'creatorId'),
    subjects: [subject('creatorId', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    // Личная задача стирается с человеком; задача организации остаётся (автор — томбстоун)
    onSubjectErasure: HARD_DELETE_PERSONAL,
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [
      deep('TaskParticipant', 'taskId'),
      deep('TaskTag', 'taskId'),
      deep('Task', 'parentId'),
      { to: 'Chat', kind: 'deep', via: 'parentId' },
      { to: 'ChatterEntry', kind: 'async_delete', via: 'refId' },
      { to: 'EscrowAgreement', kind: 'shallow', via: 'refId' },
    ],
    enforcement: batched('deletedAt', undefined, 'tasks.trash'),
    holdAware: true,
    rootEntity: true,
    exportable: 'both',
  },
  TaskParticipant: {
    owner: 'tasks',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: via('user', 'Task'),
    subjects: [subject('userId', 'participant')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  TaskTag: {
    owner: 'tasks',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: via('user', 'Task'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('tag text of the task'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },

  // ================= Календарь =================
  CalendarEvent: {
    owner: 'calendar',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [deep('CalendarEventReminder', 'eventId'), deep('CalendarEvent', 'recurrenceParentId'), deep('EventParticipant', 'eventId')],
    enforcement: batched('deletedAt', undefined, 'calendar.trash'),
    holdAware: true,
    rootEntity: true,
    exportable: 'user',
  },
  CalendarEventReminder: {
    owner: 'calendar',
    version: 1,
    dataClass: 'operational',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'recipient')],
    legalBasis: CONSENT,
    // Отправленные напоминания — 30 дней (иначе таблица растёт вечно)
    retention: forDays(30, 'event:terminal'),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('sentAt'),
    holdAware: false,
  },
  EventParticipant: {
    owner: 'calendar',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'CalendarEvent'),
    subjects: [subject('userId', 'participant')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  Resource: {
    owner: 'calendar',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: scoped('workspaceId', 'ownerId'),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE_PERSONAL,
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [shallow('CalendarEvent', 'resourceId')],
    enforcement: notEnforced('bookable resources live until removed'),
    holdAware: true,
    exportable: 'both',
  },
  GoogleConnection: {
    owner: 'calendar',
    version: 1,
    dataClass: 'auth_secret',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('integration lives until the person disconnects it'),
    holdAware: false,
  },

  // ================= Кошелёк, леджер, эскроу =================
  UserPaymentCard: {
    owner: 'wallet',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('a saved card lives until the person removes it'),
    holdAware: true,
    exportable: 'user',
  },
  Currency: {
    owner: 'wallet',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: polymorphic(['user', 'workspace'], 'issuerType', 'issuerId'),
    subjects: [subject('issuerId', 'owner')],
    legalBasis: law('kz_payments_law_art13'),
    retention: legalFloor(YEARS(5), 'event:account.closed', FOREVER),
    onSubjectErasure: retainLegal('kz_payments_law_art13', YEARS(5)),
    onTenantPurge: tenantRetain('kz_payments_law_art13', YEARS(5)),
    edges: [deep('Account', 'currencyId')],
    enforcement: notEnforced('a currency lives while any ledger account references it'),
    holdAware: true,
  },
  Account: {
    owner: 'wallet',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: { kind: 'ledger', column: 'id' },
    subjects: [subject('ownerId', 'owner')],
    legalBasis: law('kz_payments_law_art13'),
    retention: legalFloor(YEARS(5), 'event:account.closed', FOREVER),
    // Деньги не стираются: счёт остаётся, владелец — томбстоун (Σ = 0 держит двойная запись)
    onSubjectErasure: retainLegal('kz_payments_law_art13', YEARS(5)),
    onTenantPurge: tenantRetain('kz_payments_law_art13', YEARS(5)),
    edges: [{ to: 'LedgerTransfer', kind: 'shallow', via: 'debitAccountId' }, { to: 'LedgerTransfer', kind: 'shallow', via: 'creditAccountId' }],
    enforcement: notEnforced('ledger accounts are append-only history'),
    holdAware: true,
    exportable: 'both',
  },
  LedgerTransfer: {
    owner: 'wallet',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: { kind: 'ledger', column: 'debitAccountId' },
    subjects: [],
    legalBasis: law('kz_payments_law_art13'),
    retention: legalFloor(YEARS(5), 'event:account.closed', FOREVER),
    onSubjectErasure: noSubject('transfers reference accounts only; the memo is machine-readable'),
    onTenantPurge: tenantRetain('kz_payments_law_art13', YEARS(5)),
    edges: [],
    enforcement: notEnforced('append-only ledger (trigger ENABLE ALWAYS + owner role)'),
    holdAware: true,
    exportable: 'both',
  },
  EscrowAgreement: {
    owner: 'wallet',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: { kind: 'ledger', column: 'id' },
    subjects: [],
    legalBasis: law('kz_payments_law_art13'),
    retention: legalFloor(YEARS(5), 'event:record.closed', FOREVER),
    onSubjectErasure: noSubject('payers live in EscrowHold'),
    onTenantPurge: tenantRetain('kz_payments_law_art13', YEARS(5)),
    edges: [deep('EscrowHold', 'agreementId')],
    enforcement: notEnforced('escrow history is append-only except status transitions'),
    holdAware: true,
  },
  EscrowHold: {
    owner: 'wallet',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: via('ledger', 'EscrowAgreement'),
    subjects: [subject('payerUserId', 'owner')],
    legalBasis: law('kz_payments_law_art13'),
    retention: legalFloor(YEARS(5), 'parent', FOREVER),
    onSubjectErasure: retainLegal('kz_payments_law_art13', YEARS(5)),
    onTenantPurge: tenantRetain('kz_payments_law_art13', YEARS(5)),
    edges: [],
    enforcement: notEnforced('escrow history is append-only except status transitions'),
    holdAware: true,
  },

  // ================= Магазин и вишлист =================
  Shop: {
    owner: 'shop',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: polymorphic(['user', 'workspace']),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE_PERSONAL,
    onTenantPurge: tenantHook('shop.owner'),
    edges: [deep('Showcase', 'shopId')],
    enforcement: notEnforced('a storefront lives until its owner closes it'),
    holdAware: true,
    exportable: 'both',
  },
  Showcase: {
    owner: 'shop',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: via('user', 'Shop'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('storefront content'),
    onTenantPurge: CASCADE_FK,
    edges: [deep('Listing', 'showcaseId')],
    enforcement: CASCADE,
    holdAware: true,
  },
  Listing: {
    owner: 'shop',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: via('user', 'Showcase'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('storefront content'),
    onTenantPurge: CASCADE_FK,
    edges: [deep('ListingPrice', 'listingId'), shallow('Order', 'listingId'), { to: 'FileLink', kind: 'async_delete', via: 'refId' }],
    enforcement: CASCADE,
    holdAware: true,
  },
  ListingPrice: {
    owner: 'shop',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: via('user', 'Listing'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('price rows'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  Order: {
    owner: 'shop',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: byUser('buyerId'),
    subjects: [subject('buyerId', 'owner'), subject('sellerId', 'counterpart')],
    legalBasis: law('kz_279_contracts_5y'),
    // Заказ — сделка (оплата через эскроу): 5 лет после закрытия
    retention: legalFloor(YEARS(5), 'event:record.closed'),
    onSubjectErasure: retainLegal('kz_279_contracts_5y', YEARS(5)),
    onTenantPurge: tenantRetain('kz_279_contracts_5y', YEARS(5)),
    edges: [deep('OrderContribution', 'orderId'), deep('OrderPrice', 'orderId')],
    enforcement: batched('closedAt', { status: ['settled', 'rejected', 'cancelled', 'refunded'] }),
    holdAware: true,
    exportable: 'both',
  },
  OrderContribution: {
    owner: 'shop',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: via('user', 'Order'),
    subjects: [subject('contributorId', 'participant')],
    legalBasis: law('kz_279_contracts_5y'),
    retention: legalFloor(YEARS(5), 'parent'),
    onSubjectErasure: retainLegal('kz_279_contracts_5y', YEARS(5)),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  OrderPrice: {
    owner: 'shop',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: via('user', 'Order'),
    subjects: [],
    legalBasis: law('kz_279_contracts_5y'),
    retention: legalFloor(YEARS(5), 'parent'),
    onSubjectErasure: noSubject('price snapshot of the order'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  WishItem: {
    owner: 'shop',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('ownerId'),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('the wishlist lives until the owner removes items'),
    holdAware: true,
    exportable: 'user',
  },

  // ================= Скины карточек =================
  CardSkin: {
    owner: 'card-skins',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('platform catalogue of skins'),
    subjects: [subject('authorId', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: NOT_TENANT,
    edges: [deep('CardSkinInstance', 'skinId')],
    enforcement: notEnforced('catalogue items are retired, not deleted (owned instances reference them)'),
    holdAware: false,
  },
  CardSkinInstance: {
    owner: 'card-skins',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: byUser('ownerId'),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONTRACT,
    retention: keep(),
    // Куплен за платформенную валюту: экземпляр остаётся в истории, владелец — томбстоун
    onSubjectErasure: retainLegal('kz_payments_law_art13', YEARS(5)),
    onTenantPurge: NOT_TENANT,
    edges: [deep('CardSkinTransfer', 'instanceId')],
    enforcement: notEnforced('owned cosmetics are purchase history'),
    holdAware: true,
    exportable: 'user',
  },
  CardSkinTransfer: {
    owner: 'card-skins',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: via('user', 'CardSkinInstance'),
    subjects: [subject('fromUserId', 'counterpart'), subject('toUserId', 'owner')],
    legalBasis: law('kz_payments_law_art13'),
    retention: legalFloor(YEARS(5), 'created', FOREVER),
    onSubjectErasure: retainLegal('kz_payments_law_art13', YEARS(5)),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('append-only ownership history (trigger ENABLE ALWAYS)'),
    holdAware: true,
  },

  // ================= Финансы (B2C) =================
  FinBook: {
    owner: 'finances',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: polymorphic(['user', 'workspace']),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE_PERSONAL,
    onTenantPurge: tenantHook('finances.owner'),
    edges: [deep('FinAccount', 'bookId'), deep('FinBudget', 'bookId'), deep('FinPerson', 'bookId'), deep('FinRecurringRule', 'bookId'), deep('FinTransaction', 'bookId'), { to: 'FinAuditLog', kind: 'async_delete', via: 'bookId' }],
    enforcement: notEnforced('personal finance book lives until the owner deletes it'),
    holdAware: true,
    exportable: 'both',
  },
  FinAccount: {
    owner: 'finances',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'FinBook'),
    subjects: [],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('book content'),
    onTenantPurge: CASCADE_FK,
    edges: [shallow('FinAccount', 'parentId'), deep('FinTransaction', 'fromAccountId'), deep('FinTransaction', 'toAccountId')],
    enforcement: CASCADE,
    holdAware: true,
  },
  FinTransaction: {
    owner: 'finances',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'FinBook'),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: batched('deletedAt', undefined, 'finances.trash'),
    holdAware: true,
    rootEntity: true,
    exportable: 'both',
  },
  FinBudget: {
    owner: 'finances',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'FinBook'),
    subjects: [],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('book content'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  FinPerson: {
    owner: 'finances',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'FinBook'),
    subjects: [subject('userId', 'member')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  FinRecurringRule: {
    owner: 'finances',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'FinBook'),
    subjects: [],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('book content'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  FinAuditLog: {
    owner: 'finances',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: via('user', 'FinBook'),
    subjects: [subject('userId', 'actor')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: tenantHook('finances.owner'),
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },

  // ================= Диск =================
  DriveSpace: {
    owner: 'drive',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: polymorphic(['user', 'workspace']),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: tenantHook('drive.workspace'),
    edges: [deep('DriveNode', 'spaceId'), deep('DrivePhotoBucket', 'spaceId')],
    enforcement: notEnforced('a drive lives with its owner'),
    holdAware: true,
    exportable: 'both',
  },
  DriveNode: {
    owner: 'drive',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'DriveSpace'),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [deep('DriveNodeVersion', 'nodeId'), deep('DriveNode', 'parentId'), deep('DriveRecent', 'nodeId'), deep('DriveStar', 'nodeId'), { to: 'FileObject', kind: 'refcount', via: 'fileId' }],
    // Корзина 30 дней, затем поддерево и байты уходят
    enforcement: batched('trashedAt', undefined, 'drive.trash'),
    holdAware: true,
    rootEntity: true,
    exportable: 'both',
  },
  DriveNodeVersion: {
    owner: 'drive',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'DriveNode'),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [{ to: 'FileObject', kind: 'refcount', via: 'fileId' }],
    enforcement: CASCADE,
    holdAware: true,
  },
  DriveStar: {
    owner: 'drive',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  DriveRecent: {
    owner: 'drive',
    version: 1,
    dataClass: 'operational',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONSENT,
    retention: forDays(90),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: batched('openedAt'),
    holdAware: false,
  },
  DrivePhotoBucket: {
    owner: 'drive',
    version: 1,
    dataClass: 'derived',
    ownerKey: via('user', 'DriveSpace'),
    subjects: [],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('photo grid aggregate'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: false,
  },

  // ================= Заметки =================
  NoteSpace: {
    owner: 'notes',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: polymorphic(['user', 'workspace']),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: tenantHook('notes.workspace'),
    edges: [deep('NoteBoardItem', 'spaceId'), deep('NoteChunk', 'spaceId'), deep('NoteFolder', 'spaceId'), deep('Note', 'spaceId')],
    enforcement: notEnforced('a notes space lives with its owner'),
    holdAware: true,
    exportable: 'both',
  },
  NoteFolder: {
    owner: 'notes',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'NoteSpace'),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [deep('NoteFolder', 'parentId'), shallow('Note', 'folderId')],
    enforcement: batched('deletedAt', undefined, 'notes.trash'),
    holdAware: true,
    rootEntity: true,
    exportable: 'both',
  },
  Note: {
    owner: 'notes',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'NoteSpace'),
    subjects: [subject('createdById', 'author'), subject('updatedById', 'actor')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [deep('NoteBoardItem', 'noteId'), deep('NoteChunk', 'noteId'), deep('NoteLink', 'noteId'), deep('NoteRevision', 'noteId'), { to: 'FileLink', kind: 'async_delete', via: 'refId' }],
    enforcement: batched('deletedAt', undefined, 'notes.trash'),
    holdAware: true,
    rootEntity: true,
    exportable: 'both',
  },
  NoteRevision: {
    owner: 'notes',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'Note'),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  NoteLink: {
    owner: 'notes',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'Note'),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  NoteBoardItem: {
    owner: 'notes',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: via('user', 'Note'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  NoteChunk: {
    owner: 'notes',
    version: 1,
    dataClass: 'derived',
    ownerKey: via('user', 'Note'),
    subjects: [],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('derived chunks of the note text (rebuilt from the note)'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: false,
  },

  // ================= Диктофон =================
  VoiceRecording: {
    owner: 'recorder',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('ownerId'),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONSENT,
    retention: keep(),
    onSubjectErasure: HARD_DELETE,
    onTenantPurge: NOT_TENANT,
    edges: [{ to: 'FileLink', kind: 'async_delete', via: 'refId' }],
    enforcement: batched('deletedAt', undefined, 'recorder.trash'),
    holdAware: true,
    rootEntity: true,
    exportable: 'user',
  },
} satisfies Record<string, LifecyclePolicyInput>;
