// Политики хранилищ ВНЕ моделей Prisma: сырые таблицы (партиции аналитики и идемпотентности),
// профили байтов файлового движка, семейства ключей Redis (две роли: состояние ≠ кэш) и
// производные хранилища вне базы (архивы, экспорты, журнал стираний, бэкапы, логи).
// Один реестр на ВСЕ хранилища (GitLab data dictionary): новое семейство ключей или новый
// профиль файлов без строки здесь — красный `pnpm check:lifecycle`.
import {
  CASCADE,
  CONSENT,
  CONTRACT,
  ERASE_REDIS,
  FOREVER,
  NOT_TENANT,
  TRANSIENT,
  TTL,
  YEARS,
  batched,
  dropPartition,
  eraseHook,
  forDays,
  global,
  interest,
  keep,
  law,
  legalFloor,
  noSubject,
  notEnforced,
  retainLegal,
  scoped,
  shred,
  subject,
  tenantHook,
  tenantRetain,
  via,
  withParent,
} from './helpers';
import type { LifecycleDataClass, LifecyclePolicyInput, LifecycleRedisRole, LifecycleStore } from './types';

// ================= Сырые таблицы (не модели Prisma) =================
export const TABLE_LIFECYCLE = {
  'table:analytics.events': {
    store: { kind: 'table', table: 'analytics.events' },
    owner: 'core/analytics',
    version: 1,
    dataClass: 'analytics_event',
    ownerKey: scoped('workspace_id', 'user_id'),
    subjects: [subject('user_id', 'actor')],
    legalBasis: CONSENT,
    retention: forDays(400),
    // Забвение человека — джоб движка аналитики (сырьё батчами), организации — тоже
    onSubjectErasure: eraseHook('analytics.subject'),
    onTenantPurge: tenantHook('analytics.workspace'),
    edges: [],
    enforcement: dropPartition('ts', 'month'),
    holdAware: false,
  },
  'table:analytics.outbox': {
    store: { kind: 'table', table: 'analytics.outbox' },
    owner: 'core/analytics',
    version: 1,
    dataClass: 'ephemeral',
    ownerKey: global('transactional outbox of server-side analytics facts'),
    subjects: [],
    legalBasis: CONSENT,
    retention: forDays(1),
    onSubjectErasure: noSubject('rows live seconds until the consumer moves them to analytics.events'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: TRANSIENT,
    holdAware: false,
  },
  'table:idem.keys': {
    store: { kind: 'table', table: 'idem.keys' },
    owner: 'core/idempotency',
    version: 1,
    dataClass: 'operational',
    ownerKey: scoped('workspace_id', 'user_id'),
    subjects: [subject('user_id', 'actor')],
    legalBasis: interest('a repeated request must not double its effect'),
    retention: forDays(7),
    onSubjectErasure: noSubject('keys carry hashes and codes; the response snapshot is encrypted under the owner KEK'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    // HASH-партиции по ключу — сброс по времени невозможен, ночной прогон движка батчами
    enforcement: batched('expires_at', undefined, 'idempotency.keys'),
    holdAware: false,
  },
  'table:idem.responses': {
    store: { kind: 'table', table: 'idem.responses' },
    owner: 'core/idempotency',
    version: 1,
    dataClass: 'derived',
    ownerKey: scoped('scope_id'),
    subjects: [],
    legalBasis: interest('a repeated request returns the original response'),
    retention: forDays(3),
    // Снимок ответа зашифрован под KEK владельца — уничтожение KEK делает копию нечитаемой
    onSubjectErasure: shred('user'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: dropPartition('at', 'day'),
    holdAware: false,
  },
  'table:public._prisma_migrations': {
    store: { kind: 'table', table: 'public._prisma_migrations' },
    owner: 'core/database',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('schema migration history'),
    subjects: [],
    legalBasis: interest('schema history of the database'),
    retention: keep(),
    onSubjectErasure: noSubject('tooling table'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('migration history is kept forever'),
    holdAware: false,
  },
} satisfies Record<string, LifecyclePolicyInput>;

// ================= Профили байтов файлового движка =================
/** Байты живут, пока жива строка FileObject (и её последнее место — FileLink): срок у файла, не у профиля. */
function blob(profile: string, dataClass: LifecycleDataClass, extra: Partial<LifecyclePolicyInput> = {}): LifecyclePolicyInput {
  return {
    store: { kind: 'blob', profile },
    owner: 'core/files',
    version: 1,
    dataClass,
    ownerKey: via('user', 'FileObject'),
    subjects: [],
    legalBasis: CONSENT,
    retention: withParent,
    onSubjectErasure: noSubject('bytes follow their FileObject row (erased with it)'),
    onTenantPurge: tenantHook('files.owned'),
    edges: [],
    enforcement: CASCADE,
    holdAware: dataClass === 'legal_record' || dataClass === 'tenant_record' || dataClass.startsWith('user_content'),
    ...extra,
  };
}

export const BLOB_LIFECYCLE = {
  'blob:avatar': blob('avatar', 'identity_pii'),
  'blob:listing_image': blob('listing_image', 'user_content_shared'),
  'blob:chat_attachment': blob('chat_attachment', 'user_content_shared'),
  'blob:voice_message': blob('voice_message', 'user_content_shared'),
  'blob:dictaphone': blob('dictaphone', 'user_content_private'),
  'blob:document': blob('document', 'user_content_private'),
  'blob:drive_file': blob('drive_file', 'user_content_private'),
  // Предмет подписи, CMS и штамп — доказательства: вечны, как сам акт
  'blob:sign_subject': blob('sign_subject', 'legal_record', {
    legalBasis: law('kz_digital_code_art62'),
    retention: legalFloor(FOREVER, 'parent'),
    onSubjectErasure: retainLegal('kz_digital_code_art62', FOREVER),
    onTenantPurge: tenantRetain('kz_digital_code_art62', FOREVER),
  }),
  'blob:sign_cms': blob('sign_cms', 'legal_record', {
    legalBasis: law('kz_digital_code_art62'),
    retention: legalFloor(FOREVER, 'parent'),
    onSubjectErasure: retainLegal('kz_digital_code_art62', FOREVER),
    onTenantPurge: tenantRetain('kz_digital_code_art62', FOREVER),
  }),
  'blob:sign_stamped': blob('sign_stamped', 'legal_record', {
    legalBasis: law('kz_digital_code_art62'),
    retention: legalFloor(FOREVER, 'parent'),
    onSubjectErasure: retainLegal('kz_digital_code_art62', FOREVER),
    onTenantPurge: tenantRetain('kz_digital_code_art62', FOREVER),
  }),
  'blob:asset_photo': blob('asset_photo', 'tenant_record', { legalBasis: CONTRACT }),
  'blob:note_image': blob('note_image', 'user_content_private'),
  // Выгрузка журнала организации — копия улик: сутки на скачивание, дальше не нужна
  'blob:audit_export': blob('audit_export', 'security_audit', {
    legalBasis: law('kz_et832_p38'),
    retention: forDays(7),
    enforcement: batched('createdAt', undefined, 'files.deleted'),
  }),
  'blob:generic': blob('generic', 'user_content_private'),
} satisfies Record<string, LifecyclePolicyInput>;

// ================= Семейства ключей Redis =================
interface RedisFamilyDef {
  patterns: readonly string[];
  role: LifecycleRedisRole;
  maxTtlSeconds: number | null;
  owner: string;
  dataClass: LifecycleDataClass;
  /** Шаблон ключей одного человека: стирание субъекта = DEL (+ BGREWRITEAOF по расписанию) */
  subjectPattern?: string;
  reason: string;
}

function redis(family: string, d: RedisFamilyDef): LifecyclePolicyInput {
  const store: LifecycleStore = {
    kind: 'redis',
    family,
    patterns: d.patterns,
    role: d.role,
    maxTtlSeconds: d.maxTtlSeconds,
    ...(d.subjectPattern ? { subjectPattern: d.subjectPattern } : {}),
  };
  return {
    store,
    owner: d.owner,
    version: 1,
    dataClass: d.dataClass,
    ownerKey: global(d.reason),
    subjects: d.subjectPattern ? [subject('key', 'owner')] : [],
    legalBasis: interest(d.reason),
    retention: d.maxTtlSeconds === null ? keep() : forDays(Math.max(1, Math.ceil(d.maxTtlSeconds / 86_400))),
    onSubjectErasure: d.subjectPattern ? ERASE_REDIS : noSubject('keys carry no personal data (ids, counters, hashes)'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: d.maxTtlSeconds === null ? notEnforced('bounded by MAXLEN / single key, not by time') : TTL,
    holdAware: false,
  };
}

const H = 3600;
const D = 86_400;

export const REDIS_LIFECYCLE = {
  // ---- роль «состояние» (noeviction, AOF): шина, локи, лимиты, эпохи, отзывы ----
  'redis:locks': redis('locks', {
    patterns: ['cron:*', 'hr:daily-warnings', 'docs:reaper', 'doc-campaigns:daily', 'analytics:seed-system-dashboards'],
    role: 'state',
    maxTtlSeconds: 2 * H,
    owner: 'shared/redis',
    dataClass: 'ephemeral',
    reason: 'fleet-wide locks of crons (efficiency only: correctness is unique indexes and status guards)',
  }),
  'redis:event_bus': redis('event_bus', {
    patterns: ['superapp:events', 'superapp:workers'],
    role: 'state',
    maxTtlSeconds: null,
    owner: 'shared/events',
    dataClass: 'operational',
    reason: 'at-most-once event bus stream (MAXLEN-bounded)',
  }),
  'redis:analytics_stream': redis('analytics_stream', {
    patterns: ['superapp:analytics'],
    role: 'state',
    maxTtlSeconds: null,
    owner: 'core/analytics',
    dataClass: 'analytics_event',
    reason: 'ingest stream of client analytics (MAXLEN-bounded, consumer moves rows to analytics.events)',
  }),
  'redis:auth_revocation': redis('auth_revocation', {
    patterns: ['auth:revfam:*'],
    role: 'state',
    maxTtlSeconds: 31 * D,
    owner: 'core/audit',
    dataClass: 'auth_secret',
    reason: 'revoked session families (must never be evicted)',
  }),
  'redis:auth_throttle': redis('auth_throttle', {
    patterns: ['auth:fail:*', 'auth:lock:*', 'auth:locked:*', 'auth:lockp:*', 'auth:stepup:*'],
    role: 'state',
    maxTtlSeconds: 2 * D,
    owner: 'core/audit',
    dataClass: 'operational',
    reason: 'sign-in protection counters (loss would reset a lockout)',
  }),
  'redis:throttler': redis('throttler', {
    patterns: ['throttle:*'],
    role: 'state',
    maxTtlSeconds: D,
    owner: 'shared/throttler',
    dataClass: 'operational',
    reason: 'request rate limits of the HTTP throttler',
  }),
  'redis:verify': redis('verify', {
    patterns: ['verify:*'],
    role: 'state',
    maxTtlSeconds: D,
    owner: 'core/verify',
    dataClass: 'auth_secret',
    reason: 'one-time code throttles and step-up proofs',
  }),
  'redis:sms_outbound': redis('sms_outbound', {
    patterns: ['smsout:*', 'ntf:sms:*'],
    role: 'state',
    maxTtlSeconds: 2 * D,
    owner: 'core/verify',
    dataClass: 'operational',
    reason: 'anti-abuse limits of outgoing SMS',
  }),
  'redis:entitlement_epochs': redis('entitlement_epochs', {
    patterns: ['ent:catalog', 'ent:epoch:*', 'ent:expired:*', 'ent:trial-ending:*', 'ent:trial-expired:*'],
    role: 'state',
    maxTtlSeconds: null,
    owner: 'core/entitlements',
    dataClass: 'operational',
    reason: 'catalogue and subject epochs, one-shot markers (eviction would serve a stale plan or repeat a warning)',
  }),
  'redis:access_epochs': redis('access_epochs', {
    patterns: ['acl:epoch', 'acl:epoch:*'],
    role: 'state',
    maxTtlSeconds: null,
    owner: 'core/access',
    dataClass: 'operational',
    reason: 'access epochs invalidating permission caches (eviction would serve stale grants)',
  }),
  'redis:keys_state': redis('keys_state', {
    patterns: [
      'keys:epoch',
      'keys:instances',
      'keys:export:*',
      'keys:newloc:*',
      'keys:throttled:*',
      'keys:last-used',
      'keys:use-count',
      'keys:access-log',
      'keys:ensure:*',
      'keys:changed',
      'keys:fail:*',
      'keys:fail-ip:*',
      'keys:rate:*',
      'keys:stepup:*',
      'keys:webhook-manual:*',
      'keys:api-tomb:*',
    ],
    role: 'state',
    maxTtlSeconds: null,
    owner: 'core/keys',
    dataClass: 'operational',
    // Надгробие отозванного ключа — состояние безопасности: вытеснение вернуло бы снимок в кэш
    reason: 'keystore epoch, API key usage counters, auth throttles and revocation tombstones',
  }),
  'redis:audit_state': redis('audit_state', {
    // `ws:seen:*` — одноразовая отметка «впервые в организации с устройства» (30 дней): вытеснение
    // повторило бы тревогу `org.session.first_seen` организации
    patterns: ['audit:*', 'ws:seen:*'],
    role: 'state',
    maxTtlSeconds: 31 * D,
    owner: 'core/audit',
    dataClass: 'security_audit',
    subjectPattern: 'audit:ud:{user}:*',
    reason: 'detection counters, collapse windows, one-shot markers and export limits of the security log',
  }),
  'redis:notifications_state': redis('notifications_state', {
    patterns: ['ntf:thr:*', 'ntf:burst:*', 'ntf:budget:*'],
    role: 'state',
    maxTtlSeconds: D,
    owner: 'core/notifications',
    dataClass: 'operational',
    subjectPattern: 'ntf:thr:{user}:*',
    reason: 'notification collapse and throttle windows',
  }),
  'redis:platform_console': redis('platform_console', {
    patterns: ['platform:session:*', 'platform:sudo:*', 'platform:loginfail:*', 'platform:stepupfail:*', 'platform:caps:*', 'platform:rate:*', 'superapp6:platform-console'],
    role: 'state',
    maxTtlSeconds: D,
    owner: 'core/platform',
    dataClass: 'auth_secret',
    subjectPattern: 'platform:*:{user}',
    reason: 'console sessions and step-up (sudo) windows of platform staff',
  }),
  'redis:analytics_state': redis('analytics_state', {
    patterns: ['analytics:counters:*', 'analytics:job:*', 'analytics:optout:*', 'analytics-rollup:*'],
    role: 'state',
    maxTtlSeconds: 400 * D,
    owner: 'core/analytics',
    dataClass: 'analytics_event',
    subjectPattern: 'analytics:optout:{user}',
    reason: 'ingest counters, report jobs and opt-out flags',
  }),
  'redis:analytics_watermarks': redis('analytics_watermarks', {
    patterns: ['analytics:dirty-days', 'analytics:rollup:last', 'analytics:first-event'],
    role: 'state',
    maxTtlSeconds: null,
    owner: 'core/analytics',
    dataClass: 'operational',
    reason: 'rollup watermarks (single keys without TTL: once found, never change until retention)',
  }),
  'redis:wallet_state': redis('wallet_state', {
    patterns: ['wallet:reconcile:*'],
    role: 'state',
    maxTtlSeconds: null,
    owner: 'wallet',
    dataClass: 'operational',
    reason: 'ledger reconciliation watermark',
  }),
  'redis:office_state': redis('office_state', {
    patterns: ['office:reconcile:*'],
    role: 'state',
    maxTtlSeconds: null,
    owner: 'office',
    dataClass: 'operational',
    reason: 'reconciliation cursor of meeting rooms',
  }),
  'redis:socket_adapter': redis('socket_adapter', {
    patterns: ['socket.io*', 'presence:changed'],
    role: 'state',
    maxTtlSeconds: null,
    owner: 'core/realtime',
    dataClass: 'ephemeral',
    reason: 'pub/sub channels of the socket.io adapter (no stored keys)',
  }),
  'redis:visibility_state': redis('visibility_state', {
    patterns: ['vis:det:*'],
    role: 'state',
    maxTtlSeconds: H + 60,
    owner: 'core/visibility',
    dataClass: 'security_audit',
    subjectPattern: 'vis:det:*:{user}*',
    reason: 'detection windows and pauses of field reveals, PII scraping and number lookups (eviction would lift a pause)',
  }),
  'redis:lifecycle_state': redis('lifecycle_state', {
    patterns: ['lifecycle:*'],
    role: 'state',
    maxTtlSeconds: 31 * D,
    owner: 'core/lifecycle',
    dataClass: 'operational',
    reason: 'purge runner pacing, canary markers and dashboard aggregates',
  }),

  // ---- роль «кэш» (allkeys-lfu, без персистентности): только то, что можно потерять ----
  'redis:auth_alive': redis('auth_alive', {
    patterns: ['auth:alive:*'],
    role: 'cache',
    maxTtlSeconds: 10 * 60,
    owner: 'core/users',
    dataClass: 'ephemeral',
    subjectPattern: 'auth:alive:{user}',
    reason: 'cached «account is alive» answer of the JWT guard',
  }),
  'redis:keys_cache': redis('keys_cache', {
    patterns: ['keys:api:*'],
    role: 'cache',
    maxTtlSeconds: H,
    owner: 'core/keys',
    dataClass: 'derived',
    reason: 'snapshot of an API key for authentication (rebuilt from the database)',
  }),
  'redis:access_cache': redis('access_cache', {
    patterns: ['acl:chk:*'],
    role: 'cache',
    maxTtlSeconds: H,
    owner: 'core/access',
    dataClass: 'derived',
    reason: 'permission check cache (versioned by access epochs)',
  }),
  'redis:entitlement_cache': redis('entitlement_cache', {
    patterns: ['ent:snap:*'],
    role: 'cache',
    maxTtlSeconds: H,
    owner: 'core/entitlements',
    dataClass: 'derived',
    reason: 'plan snapshots (versioned by entitlement epochs)',
  }),
  'redis:visibility_cache': redis('visibility_cache', {
    patterns: ['vis:policy:*', 'vis:facts:*'],
    role: 'cache',
    maxTtlSeconds: H,
    owner: 'core/visibility',
    dataClass: 'derived',
    subjectPattern: 'vis:facts:*:{user}:*',
    reason: 'field visibility policy and fact caches',
  }),
  'redis:user_cache': redis('user_cache', {
    patterns: ['user:*'],
    role: 'cache',
    maxTtlSeconds: H,
    owner: 'core/users',
    dataClass: 'identity_pii',
    subjectPattern: 'user:{user}:*',
    reason: 'profile and role caches of a person',
  }),
  'redis:presence': redis('presence', {
    patterns: ['presence:*'],
    role: 'cache',
    // «Был в сети» живёт 30 дней (`PRESENCE.LAST_SEEN_TTL_SECONDS`); счётчик соединений — минуты
    maxTtlSeconds: 31 * D,
    owner: 'messenger',
    dataClass: 'ephemeral',
    subjectPattern: 'presence:{user}:*',
    reason: 'last-seen presence of a person',
  }),
  'redis:seen_throttle': redis('seen_throttle', {
    patterns: ['sess:seen:*'],
    role: 'cache',
    maxTtlSeconds: 10 * 60,
    owner: 'core/audit',
    dataClass: 'ephemeral',
    reason: 'write throttle of the session last-seen column (eviction costs one extra UPDATE)',
  }),
  'redis:consents_gate': redis('consents_gate', {
    patterns: ['consents:*'],
    role: 'cache',
    maxTtlSeconds: H,
    owner: 'core/consents',
    dataClass: 'derived',
    reason: 'consent gate epochs cached per session (rebuilt from the database)',
  }),
  'redis:org_graph': redis('org_graph', {
    patterns: ['org:graph:*'],
    role: 'cache',
    maxTtlSeconds: H,
    owner: 'staff',
    dataClass: 'derived',
    reason: 'snapshot of the organisation structure graph',
  }),
  'redis:analytics_cache': redis('analytics_cache', {
    patterns: ['analytics:q:*'],
    role: 'cache',
    // Результат за закрытый диапазон живёт сутки (данные прошлого не меняются до роллапа)
    maxTtlSeconds: D,
    owner: 'core/analytics',
    dataClass: 'derived',
    reason: 'cached analytics report results (k-anonymous aggregates)',
  }),
  'redis:docs_discovery': redis('docs_discovery', {
    patterns: ['docs:discovery:*'],
    role: 'cache',
    maxTtlSeconds: H,
    owner: 'core/docs',
    dataClass: 'derived',
    reason: 'cached WOPI discovery of the document editor',
  }),

  // ---- чужие ключи в общем dev-Redis (в проде у LiveKit свой Redis) ----
  'redis:livekit': redis('livekit', {
    patterns: ['nodes', 'livekit_version', 'room*', 'participant*', 'agent*', 'egress*', 'ingress*', 'node_*', 'ps_*'],
    role: 'external',
    maxTtlSeconds: null,
    owner: 'core/calls',
    dataClass: 'ephemeral',
    reason: 'LiveKit SFU state (external component; its own Redis in production)',
  }),
} satisfies Record<string, LifecyclePolicyInput>;

// ================= Производные хранилища вне базы =================
function derived(name: string, location: string, extra: Omit<LifecyclePolicyInput, 'store' | 'version'>): LifecyclePolicyInput {
  return { store: { kind: 'derived', name, location }, version: 1, ...extra };
}

export const DERIVED_LIFECYCLE = {
  'derived:audit_archive': derived('audit_archive', 'object storage audit/archive/<partition> (NDJSON.gz + signed manifest)', {
    owner: 'core/audit',
    dataClass: 'security_audit',
    ownerKey: global('archived partitions of the security log'),
    subjects: [],
    legalBasis: law('kz_et832_p38'),
    retention: legalFloor(YEARS(3), 'created'),
    onSubjectErasure: retainLegal('kz_et832_p38', YEARS(3)),
    onTenantPurge: tenantRetain('kz_et832_p38', YEARS(3)),
    edges: [],
    enforcement: notEnforced('archive objects are deleted by core/audit after the legal term (owner function)'),
    holdAware: true,
  }),
  'derived:audit_digests': derived('audit_digests', 'object storage audit/digests/<yyyy>/<mm>/<id>.json', {
    owner: 'core/audit',
    dataClass: 'security_audit',
    ownerKey: global('off-database copies of integrity digests'),
    subjects: [],
    legalBasis: law('kz_et832_p38'),
    retention: legalFloor(FOREVER, 'created'),
    onSubjectErasure: noSubject('hashes only'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('integrity evidence is kept forever'),
    holdAware: true,
  }),
  'derived:lifecycle_archive': derived('lifecycle_archive', 'object storage lifecycle/archive/<table>/<partition> (NDJSON.gz + signed manifest)', {
    owner: 'core/lifecycle',
    dataClass: 'derived',
    ownerKey: global('cold tier of partitioned logs'),
    subjects: [],
    legalBasis: interest('cold tier of logs kept past their hot window'),
    retention: keep(),
    onSubjectErasure: noSubject('archived rows follow the policy of their source table'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('each archive carries the retention of its source policy'),
    holdAware: true,
  }),
  'derived:lifecycle_exports': derived('lifecycle_exports', 'object storage exports/<exportId>/ (ZIP parts + manifest.json)', {
    owner: 'core/lifecycle',
    dataClass: 'user_content_private',
    ownerKey: global('data exports of a person or an organisation (isolated prefix per export)'),
    subjects: [subject('subjectId', 'owner')],
    legalBasis: law('kz_pd_law_art12'),
    retention: forDays(7),
    onSubjectErasure: eraseHook('lifecycle.exports'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('expiresAt', undefined, 'lifecycle.exports'),
    holdAware: true,
  }),
  'derived:erasure_journal': derived('erasure_journal', 'object storage lifecycle/erasure-journal/ in BOTH backup repositories (NDJSON)', {
    owner: 'core/lifecycle',
    dataClass: 'security_audit',
    ownerKey: global('journal of erasures replayed after any restore'),
    subjects: [],
    legalBasis: law('kz_pd_law_art8_7'),
    retention: legalFloor(FOREVER, 'created'),
    onSubjectErasure: noSubject('pseudonyms and key ids only'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('the journal must outlive every backup it has to correct'),
    holdAware: true,
  }),
  'derived:backups': derived('backups', 'pgBackRest repo1 (city 1) + repo2 (city 2), encrypted, Object Lock', {
    owner: 'core/lifecycle',
    dataClass: 'derived',
    ownerKey: global('physical backups of the whole database'),
    subjects: [],
    legalBasis: interest('disaster recovery'),
    // Обещание человеку: из живых систем ≤ 30 дней, из бэкапов ≤ 35 дней после
    retention: forDays(35),
    onSubjectErasure: noSubject('expires with the 35-day window; the erasure journal is replayed after restore'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: TTL,
    holdAware: false,
  }),
  'derived:app_logs': derived('app_logs', 'application logs (stdout → log store in Kazakhstan)', {
    owner: 'core/lifecycle',
    dataClass: 'operational',
    ownerKey: global('application logs without personal data'),
    subjects: [],
    legalBasis: interest('operations and incident response'),
    retention: forDays(30),
    onSubjectErasure: noSubject('logs carry no personal data (authorization/cookie headers are banned by the linter)'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: TTL,
    holdAware: false,
  }),
  'derived:upload_tmp': derived('upload_tmp', 'temporary directory of multipart uploads (os tmp)', {
    owner: 'core/files',
    dataClass: 'ephemeral',
    ownerKey: global('bytes in flight of an upload'),
    subjects: [],
    legalBasis: CONSENT,
    retention: forDays(1),
    onSubjectErasure: noSubject('swept within 24 hours'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: batched('mtime', undefined, 'files.upload-tmp'),
    holdAware: false,
  }),
  'derived:call_egress': derived('call_egress', 'LiveKit egress directory (call recordings before ingestion)', {
    owner: 'core/calls',
    dataClass: 'ephemeral',
    ownerKey: global('recording bytes before they become a FileObject'),
    subjects: [],
    legalBasis: CONSENT,
    retention: forDays(1),
    onSubjectErasure: noSubject('ingested into core/files, then removed'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: TRANSIENT,
    holdAware: false,
  }),
} satisfies Record<string, LifecyclePolicyInput>;
