// Политики жизненного цикла ОРГАНИЗАЦИЙ (B2B): карточка и члены, юрлица и счета, штат и
// оргструктура, объекты, смены и табель, оборудование, контрагенты, документооборот, КЭДО,
// процессы, виртуальный офис. Кадровые и хозяйственные записи — по закону РК (пол срока
// реестра нельзя опустить ни организации, ни тарифу); при удалении организации её архив
// уходит вместе с ней — выгрузка архива до удаления — обязанность работодателя.
import {
  BY_REFERENCE,
  CASCADE,
  CASCADE_FK,
  CONTRACT,
  FOREVER,
  NOT_TENANT,
  YEARS,
  batched,
  byUser,
  byWorkspace,
  deep,
  eraseBy,
  eraseHook,
  forDays,
  global,
  keep,
  law,
  legalFloor,
  noSubject,
  notEnforced,
  retainLegal,
  shallow,
  shred,
  subject,
  tenantBatched,
  tenantHook,
  via,
  withParent,
} from './helpers';
import type { LifecyclePolicyInput } from './types';

export const WORKSPACES_LIFECYCLE = {
  // ================= Организация и члены =================
  Workspace: {
    owner: 'workspaces',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace('id'),
    subjects: [subject('ownerId', 'owner')],
    legalBasis: CONTRACT,
    // Архив 90 дней (восстановление владельцем), затем каскад окончательного удаления
    retention: forDays(90, 'event:archived'),
    onSubjectErasure: noSubject('the owner cannot be erased while owning (blocker sole_owner): ownership moves first'),
    onTenantPurge: tenantHook('workspaces.row'),
    edges: [
      deep('AssetModel', 'workspaceId'),
      deep('AssetMove', 'workspaceId'),
      deep('AssetServiceRecord', 'workspaceId'),
      deep('Asset', 'workspaceId'),
      deep('Bot', 'workspaceId'),
      deep('Counterparty', 'workspaceId'),
      deep('DocCampaign', 'workspaceId'),
      deep('DocTemplateLibraryInstall', 'workspaceId'),
      deep('DocTemplate', 'workspaceId'),
      deep('DocType', 'workspaceId'),
      deep('HrActionBatch', 'workspaceId'),
      deep('HrAction', 'workspaceId'),
      deep('Employment', 'workspaceId'),
      deep('EsutdSubmission', 'workspaceId'),
      deep('LegalEntity', 'workspaceId'),
      deep('LifecycleSetting', 'workspaceId'),
      deep('OfficeRoom', 'workspaceId'),
      deep('OrgDocument', 'workspaceId'),
      deep('ShiftAttendance', 'workspaceId'),
      deep('ShiftPattern', 'workspaceId'),
      deep('ShiftTemplate', 'workspaceId'),
      deep('Shift', 'workspaceId'),
      deep('StaffAssignment', 'workspaceId'),
      deep('StaffBranch', 'workspaceId'),
      deep('StaffDepartment', 'workspaceId'),
      deep('StaffDeputy', 'workspaceId'),
      deep('StaffPosition', 'workspaceId'),
      deep('StaffRate', 'workspaceId'),
      deep('StaffingPosition', 'workspaceId'),
      shallow('Task', 'workspaceId'),
      deep('WebhookEndpoint', 'workspaceId'),
      deep('WorkspaceBankAccount', 'workspaceId'),
      deep('WorkspaceInvitation', 'workspaceId'),
      deep('WorkspaceKeyPolicy', 'workspaceId'),
      deep('WorkspaceMember', 'workspaceId'),
      deep('WorkspaceNotificationPolicy', 'workspaceId'),
      deep('WorkspaceVisibilitySettings', 'workspaceId'),
      // Без FK на организацию (колонка или полиморфный владелец) — каскад по реестру
      { to: 'Chat', kind: 'deep', via: 'workspaceId' },
      { to: 'SearchDocument', kind: 'async_delete', via: 'workspaceId' },
      { to: 'ChatterEntry', kind: 'deep', via: 'workspaceId' },
      { to: 'NotificationEvent', kind: 'deep', via: 'workspaceId' },
      { to: 'Notification', kind: 'async_delete', via: 'workspaceId' },
      { to: 'CallSession', kind: 'deep', via: 'workspaceId' },
      { to: 'ApprovalRequest', kind: 'deep', via: 'workspaceId' },
      { to: 'SignRequest', kind: 'shallow', via: 'workspaceId' },
      { to: 'ProcessDefinition', kind: 'deep', via: 'workspaceId' },
      { to: 'ProcessInstance', kind: 'deep', via: 'workspaceId' },
      { to: 'ProcessTrigger', kind: 'deep', via: 'workspaceId' },
      { to: 'ProcessCredential', kind: 'deep', via: 'workspaceId' },
      { to: 'Resource', kind: 'deep', via: 'workspaceId' },
      { to: 'DriveSpace', kind: 'deep', via: 'ownerId' },
      { to: 'NoteSpace', kind: 'deep', via: 'ownerId' },
      { to: 'FinBook', kind: 'deep', via: 'ownerId' },
      { to: 'FileObject', kind: 'refcount', via: 'ownerId' },
      { to: 'Document', kind: 'deep', via: 'ownerId' },
      { to: 'Shop', kind: 'deep', via: 'ownerId' },
      { to: 'Account', kind: 'shallow', via: 'ownerId' },
      { to: 'ShareLink', kind: 'deep', via: 'ownerId' },
      { to: 'ShareLinkGuest', kind: 'deep', via: 'ownerId' },
      { to: 'VisibilityPolicy', kind: 'deep', via: 'ownerId' },
      { to: 'UserRole', kind: 'deep', via: 'tenantId' },
      { to: 'RelationTuple', kind: 'async_delete', via: 'resourceId' },
      { to: 'RelationTuple', kind: 'async_delete', via: 'subjectId' },
      { to: 'SubjectSubscription', kind: 'deep', via: 'subjectId' },
      { to: 'EntitlementGrant', kind: 'deep', via: 'subjectId' },
      { to: 'EntitlementOverride', kind: 'deep', via: 'subjectId' },
      { to: 'QuotaCounter', kind: 'deep', via: 'subjectId' },
      { to: 'LifecycleExport', kind: 'deep', via: 'subjectId' },
      // Роллапы с измерением организации уходят целиком (уникум роллапа не пережил бы NULL)
      { to: 'AnalyticsRollupEventDay', kind: 'async_delete', via: 'workspaceId' },
      { to: 'AnalyticsRollupActorDay', kind: 'async_delete', via: 'workspaceId' },
      { to: 'AnalyticsRollupSessionDay', kind: 'async_delete', via: 'workspaceId' },
      { to: 'ConsentAcceptance', kind: 'shallow', via: 'subjectId' },
      { to: 'SecurityEvent', kind: 'shallow', via: 'workspaceId' },
      { to: 'SecurityAlert', kind: 'shallow', via: 'workspaceId' },
      { to: 'ApiKey', kind: 'deep', via: 'workspaceId' },
      { to: 'PersonalDocRecord', kind: 'shallow', via: 'workspaceId' },
      { to: 'Currency', kind: 'shallow', via: 'issuerId' },
      { to: 'table:analytics.events', kind: 'async_delete', via: 'workspace_id' },
      { to: 'table:idem.keys', kind: 'async_delete', via: 'workspace_id' },
      { to: 'table:idem.responses', kind: 'shallow', via: 'scope_id' },
    ],
    enforcement: batched('archivedAt', undefined, 'workspaces.purge'),
    holdAware: true,
    exportable: 'workspace',
  },
  WorkspaceMember: {
    owner: 'workspaces',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('userId', 'member')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: eraseHook('workspaces.subject'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  WorkspaceInvitation: {
    owner: 'workspaces',
    version: 1,
    dataClass: 'operational',
    ownerKey: byWorkspace(),
    subjects: [subject('invitedBy', 'actor'), subject('toUserId', 'recipient')],
    legalBasis: CONTRACT,
    retention: forDays(30, 'event:expired'),
    onSubjectErasure: eraseBy('toUserId'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: batched('expiresAt'),
    holdAware: false,
  },
  LegalEntity: {
    owner: 'workspaces',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('legal entity of the organisation (public registry data)'),
    onTenantPurge: CASCADE_FK,
    edges: [shallow('Asset', 'balanceLegalEntityId'), deep('Employment', 'legalEntityId'), shallow('StaffBranch', 'legalEntityId'), deep('WorkspaceBankAccount', 'legalEntityId')],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  WorkspaceBankAccount: {
    owner: 'workspaces',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: byWorkspace(),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    // Реквизиты зашифрованы под KEK организации — уничтожение KEK делает копии нечитаемыми везде
    onSubjectErasure: shred('workspace'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },

  // ================= Штат и оргструктура =================
  StaffDepartment: {
    owner: 'staff',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('structure of the organisation'),
    onTenantPurge: CASCADE_FK,
    edges: [
      shallow('StaffDepartment', 'parentId'),
      shallow('StaffPosition', 'departmentId'),
      // Кортежи прав оси (department#member|head, гранты отделу) — без FK, их добирает loose FK
      { to: 'RelationTuple', kind: 'async_delete', via: 'resourceId' },
      { to: 'RelationTuple', kind: 'async_delete', via: 'subjectId' },
    ],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  StaffPosition: {
    owner: 'staff',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('structure of the organisation'),
    onTenantPurge: CASCADE_FK,
    edges: [
      deep('Shift', 'positionId'),
      deep('StaffAssignment', 'positionId'),
      shallow('StaffBranch', 'headPositionId'),
      shallow('StaffDepartment', 'headPositionId'),
      deep('StaffDeputy', 'deputyPositionId'),
      deep('StaffDeputy', 'positionId'),
      shallow('StaffPosition', 'reportsToPositionId'),
      deep('StaffingPosition', 'positionId'),
      shallow('WorkspaceInvitation', 'positionId'),
      // Кортежи прав оси (position#holder, гранты должности) — без FK, их добирает loose FK
      { to: 'RelationTuple', kind: 'async_delete', via: 'resourceId' },
      { to: 'RelationTuple', kind: 'async_delete', via: 'subjectId' },
    ],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  StaffBranch: {
    owner: 'objects',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('physical sites of the organisation'),
    onTenantPurge: CASCADE_FK,
    edges: [
      deep('Asset', 'branchId'),
      deep('ShiftAttendance', 'branchId'),
      deep('ShiftPattern', 'branchId'),
      deep('ShiftTemplate', 'branchId'),
      deep('Shift', 'branchId'),
      deep('StaffAssignment', 'branchId'),
      deep('StaffBranch', 'parentId'),
      deep('StaffDeputy', 'branchId'),
      deep('StaffingPosition', 'branchId'),
      // Кортежи прав оси (branch#member|head, гранты объекту) — без FK, их добирает loose FK
      { to: 'RelationTuple', kind: 'async_delete', via: 'resourceId' },
      { to: 'RelationTuple', kind: 'async_delete', via: 'subjectId' },
    ],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  StaffAssignment: {
    owner: 'staff',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('userId', 'employee')],
    legalBasis: CONTRACT,
    retention: withParent,
    // Назначение ушедшего человека снимается; кадровый след живёт в Employment / HrAction (по закону)
    onSubjectErasure: noSubject('organization HR record: the active assignment ends at the erasure', 'staff.subject'),
    onTenantPurge: CASCADE_FK,
    edges: [deep('ShiftPattern', 'assignmentId'), shallow('Shift', 'assignmentId'), deep('StaffRate', 'assignmentId')],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  StaffingPosition: {
    owner: 'objects',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [deep('ShiftPattern', 'staffingPositionId'), shallow('Shift', 'staffingPositionId'), shallow('StaffAssignment', 'staffingPositionId'), deep('StaffRate', 'staffingPositionId')],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  StaffRate: {
    owner: 'objects',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  StaffDeputy: {
    owner: 'staff',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('deputyUserId', 'employee'), subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('organization record: active deputyships of the person end at the erasure', 'staff.subject'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },

  // ================= Смены и табель =================
  ShiftTemplate: {
    owner: 'objects',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [shallow('Shift', 'templateId'), shallow('StaffingPosition', 'shiftTemplateId')],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  ShiftPattern: {
    owner: 'objects',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [shallow('Shift', 'patternId')],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  Shift: {
    owner: 'objects',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('userId', 'employee'), subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [shallow('ShiftAttendance', 'shiftId')],
    enforcement: notEnforced('the schedule is kept with the timesheet it produced'),
    holdAware: true,
    exportable: 'workspace',
  },
  ShiftAttendance: {
    owner: 'objects',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: byWorkspace(),
    subjects: [subject('userId', 'employee')],
    legalBasis: law('kz_279_timesheets_5y'),
    // Табель — 5 лет (279-НҚ); работы с вредными условиями — 75 (тип записи решает позже)
    retention: legalFloor(YEARS(5), 'created'),
    onSubjectErasure: retainLegal('kz_279_timesheets_5y', YEARS(5)),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: batched('localDate'),
    holdAware: true,
    exportable: 'both',
  },

  // ================= Оборудование =================
  AssetModel: {
    owner: 'objects',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [deep('Asset', 'modelId')],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  Asset: {
    owner: 'objects',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('custodianUserId', 'employee'), subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [deep('AssetMove', 'assetId'), deep('AssetServiceRecord', 'assetId'), shallow('Asset', 'parentAssetId')],
    enforcement: notEnforced('equipment register of the organisation'),
    holdAware: true,
    exportable: 'workspace',
  },
  AssetMove: {
    owner: 'objects',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('fromUserId', 'employee'), subject('toUserId', 'employee')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  AssetServiceRecord: {
    owner: 'objects',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },

  // ================= Контрагенты =================
  Counterparty: {
    owner: 'counterparties',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    // ПДн стороны договора зашифрованы под KEK организации (субъект — не пользователь платформы)
    onSubjectErasure: shred('workspace'),
    onTenantPurge: CASCADE_FK,
    edges: [
      shallow('AssetServiceRecord', 'counterpartyId'),
      shallow('Asset', 'holdingCounterpartyId'),
      deep('CounterpartyBankAccount', 'counterpartyId'),
      deep('CounterpartyContact', 'counterpartyId'),
    ],
    enforcement: notEnforced('reference book of the organisation (archived, not deleted)'),
    holdAware: true,
    exportable: 'workspace',
  },
  CounterpartyContact: {
    owner: 'counterparties',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: via('workspace', 'Counterparty'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: shred('workspace'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  CounterpartyBankAccount: {
    owner: 'counterparties',
    version: 1,
    dataClass: 'financial_record',
    ownerKey: via('workspace', 'Counterparty'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: shred('workspace'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },

  // ================= Документооборот =================
  DocType: {
    owner: 'documents',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('document kinds of the organisation'),
    onTenantPurge: CASCADE_FK,
    edges: [deep('DocTemplate', 'docTypeId'), deep('DocTypeCounter', 'docTypeId'), deep('OrgDocument', 'docTypeId')],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  DocTypeCounter: {
    owner: 'documents',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: via('workspace', 'DocType'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('numbering counter'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  DocTemplate: {
    owner: 'documents',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [shallow('OrgDocument', 'templateId'), { to: 'FileObject', kind: 'refcount', via: 'fileId' }],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  OrgDocument: {
    owner: 'documents',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: byWorkspace(),
    subjects: [subject('subjectUserId', 'employee'), subject('createdById', 'author')],
    legalBasis: law('kz_279_contracts_5y'),
    // Хозяйственные договоры и первичка — 5 лет после события; кадровые виды — 75 (вид решает)
    retention: legalFloor(YEARS(5), 'event:record.closed', FOREVER),
    onSubjectErasure: retainLegal('kz_279_contracts_5y', YEARS(5)),
    onTenantPurge: CASCADE_FK,
    edges: [shallow('OrgDocument', 'parentDocumentId'), { to: 'FileObject', kind: 'refcount', via: 'fileId' }],
    enforcement: notEnforced('legal records are archived, never purged while the organisation lives'),
    holdAware: true,
    exportable: 'both',
  },
  DocCampaign: {
    owner: 'hr',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [deep('DocCampaignTarget', 'campaignId')],
    enforcement: notEnforced('familiarisation campaigns are HR evidence'),
    holdAware: true,
    exportable: 'workspace',
  },
  DocCampaignTarget: {
    owner: 'hr',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: via('workspace', 'DocCampaign'),
    subjects: [subject('userId', 'employee')],
    legalBasis: law('kz_279_personnel_75y'),
    retention: legalFloor(YEARS(75), 'parent'),
    onSubjectErasure: retainLegal('kz_279_personnel_75y', YEARS(75)),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'both',
  },
  DocTemplateLibraryInstall: {
    owner: 'documents',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: noSubject('library install marker'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },

  // ================= КЭДО =================
  Employment: {
    owner: 'hr',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: byWorkspace(),
    subjects: [subject('userId', 'employee'), subject('createdById', 'author')],
    legalBasis: law('kz_279_personnel_75y'),
    retention: legalFloor(YEARS(75), 'event:employment.ended'),
    onSubjectErasure: retainLegal('kz_279_personnel_75y', YEARS(75)),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: notEnforced('personnel records: 75 years after employment ends (279-NK)'),
    holdAware: true,
    exportable: 'both',
  },
  HrAction: {
    owner: 'hr',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: byWorkspace(),
    subjects: [subject('userId', 'employee'), subject('createdById', 'author')],
    legalBasis: law('kz_279_personnel_75y'),
    retention: legalFloor(YEARS(75), 'event:employment.ended'),
    onSubjectErasure: retainLegal('kz_279_personnel_75y', YEARS(75)),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: notEnforced('personnel orders: 75 years (279-NK)'),
    holdAware: true,
    exportable: 'both',
  },
  HrActionBatch: {
    owner: 'hr',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: notEnforced('batch container of personnel orders'),
    holdAware: true,
  },
  EsutdSubmission: {
    owner: 'hr',
    version: 1,
    dataClass: 'legal_record',
    ownerKey: byWorkspace(),
    subjects: [subject('userId', 'employee')],
    legalBasis: law('kz_279_employment_contracts'),
    retention: legalFloor(YEARS(75), 'event:employment.ended'),
    onSubjectErasure: retainLegal('kz_279_employment_contracts', YEARS(75)),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: notEnforced('state registry submissions follow the employment contract term'),
    holdAware: true,
  },
  PersonalDocRecord: {
    owner: 'hr',
    version: 1,
    dataClass: 'user_content_private',
    ownerKey: byUser('userId'),
    subjects: [subject('userId', 'owner')],
    legalBasis: CONTRACT,
    // Копии кадровых документов в «Моих документах» человека — его личный архив: переживает
    // организацию и стирается вместе с его аккаунтом
    retention: keep(),
    onSubjectErasure: eraseHook('hr.subject'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('personal archive of the employee'),
    holdAware: true,
    exportable: 'user',
  },
  WorkCalendarDay: {
    owner: 'hr',
    version: 1,
    dataClass: 'operational',
    ownerKey: global('production calendar of Kazakhstan (reference data)'),
    subjects: [],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: noSubject('reference data'),
    onTenantPurge: NOT_TENANT,
    edges: [],
    enforcement: notEnforced('reference data'),
    holdAware: false,
  },

  // ================= Процессы =================
  ProcessDefinition: {
    owner: 'processes',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [deep('ProcessInstance', 'definitionId'), deep('ProcessTrigger', 'definitionId'), deep('ProcessVersion', 'definitionId')],
    enforcement: notEnforced('process designs of the organisation'),
    holdAware: true,
    exportable: 'workspace',
  },
  ProcessVersion: {
    owner: 'processes',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: via('workspace', 'ProcessDefinition'),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [deep('ProcessInstance', 'versionId')],
    enforcement: CASCADE,
    holdAware: true,
    exportable: 'workspace',
  },
  ProcessInstance: {
    owner: 'processes',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: noSubject('run state; people live in step runs'),
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [deep('ProcessStepRun', 'instanceId')],
    enforcement: notEnforced('process runs are kept with their definition'),
    holdAware: true,
    exportable: 'workspace',
  },
  ProcessStepRun: {
    owner: 'processes',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: via('workspace', 'ProcessInstance'),
    subjects: [subject('assigneeId', 'recipient'), subject('claimedById', 'actor')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  ProcessTrigger: {
    owner: 'processes',
    version: 1,
    dataClass: 'tenant_record',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
  ProcessCredential: {
    owner: 'processes',
    version: 1,
    dataClass: 'auth_secret',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: tenantBatched('workspaceId'),
    edges: [],
    enforcement: notEnforced('integration credentials live until the organisation removes them'),
    holdAware: false,
  },

  // ================= Виртуальный офис =================
  OfficeRoom: {
    owner: 'office',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: byWorkspace(),
    subjects: [subject('createdById', 'author')],
    legalBasis: CONTRACT,
    retention: keep(),
    onSubjectErasure: BY_REFERENCE,
    onTenantPurge: CASCADE_FK,
    edges: [deep('OfficeRoomParticipant', 'roomId'), { to: 'Chat', kind: 'deep', via: 'parentId' }],
    enforcement: notEnforced('meeting history of the organisation'),
    holdAware: true,
    exportable: 'workspace',
  },
  OfficeRoomParticipant: {
    owner: 'office',
    version: 1,
    dataClass: 'user_content_shared',
    ownerKey: via('workspace', 'OfficeRoom'),
    subjects: [subject('userId', 'participant')],
    legalBasis: CONTRACT,
    retention: withParent,
    onSubjectErasure: eraseBy('userId'),
    onTenantPurge: CASCADE_FK,
    edges: [],
    enforcement: CASCADE,
    holdAware: true,
  },
} satisfies Record<string, LifecyclePolicyInput>;
